package org.openemr2026.emergency;

import java.nio.charset.StandardCharsets; import java.security.*; import java.time.*; import java.util.*;
import org.openemr2026.contracts.*; import org.openemr2026.security.ClinicalIdentity;
import org.springframework.jdbc.core.simple.JdbcClient; import org.springframework.stereotype.Service; import org.springframework.transaction.support.TransactionTemplate;

@Service
final class EmergencyCoordinationService {
    private final JdbcClient jdbc; private final TransactionTemplate transactions;
    EmergencyCoordinationService(JdbcClient jdbc, TransactionTemplate transactions) { this.jdbc = jdbc; this.transactions = transactions; }

    EmergencyCoordinationCaseWire create(ClinicalIdentity identity, String key, EmergencyCoordinationCaseCreateRequestWire request) {
        validate(request.patientId(), request.encounterId(), request.facilityId(), request.caseType(), request.priority(), request.targetUnit(), request.summary(), request.riskSummary(), request.dueAt());
        requireEncounter(identity.tenantId(), request.patientId(), request.encounterId(), request.facilityId()); requireUser(identity.tenantId(), request.requestedTo());
        return transactions.execute(status -> { begin(identity, "EMERGENCY_COORDINATION_CREATE", key, sha256(request.patientId()+"|"+request.encounterId()+"|"+request.caseType()+"|"+request.targetUnit()+"|"+request.dueAt())); UUID id=UUID.randomUUID(); jdbc.sql("""
            insert into emergency_coordination_case(tenant_id, coordination_case_id, patient_id, encounter_id, facility_id, case_type, priority, target_unit, requested_to, summary, risk_summary, due_at, status, requested_by)
            values (:tenant,:id,:patient,:encounter,:facility,:type,:priority,:target,:requested_to,:summary,:risk,:due,'OPEN',:actor)
            """).param("tenant",identity.tenantId()).param("id",id).param("patient",request.patientId()).param("encounter",request.encounterId()).param("facility",request.facilityId()).param("type",request.caseType().name()).param("priority",request.priority().name()).param("target",request.targetUnit().trim()).param("requested_to",request.requestedTo()).param("summary",request.summary().trim()).param("risk",request.riskSummary().trim()).param("due",request.dueAt().atOffset(ZoneOffset.UTC)).param("actor",identity.userId()).update(); evidence(identity,request.patientId(),id,"EMERGENCY_COORDINATION_CREATED"); complete(identity,"EMERGENCY_COORDINATION_CREATE",key,id); return find(identity.tenantId(),id,request.patientId()); });
    }

    EmergencyCoordinationCaseWire update(ClinicalIdentity identity, String key, UUID id, EmergencyCoordinationCaseUpdateRequestWire request) {
        validate(request.patientId(),request.encounterId(),request.facilityId(),"UPDATE",request.priority(),request.targetUnit(),request.summary(),request.riskSummary(),request.dueAt()); requireUser(identity.tenantId(),request.requestedTo());
        return transactions.execute(status -> { begin(identity,"EMERGENCY_COORDINATION_UPDATE",key,sha256(id+"|"+request.expectedRowVersion()+"|"+request.summary())); Head head=lock(identity,id,request.patientId(),request.encounterId(),request.facilityId()); requireVersion(head,request.expectedRowVersion()); if(!"OPEN".equals(head.status())) throw state("Only an open coordination case can be edited"); jdbc.sql("""
            update emergency_coordination_case set priority=:priority,target_unit=:target,requested_to=:requested_to,summary=:summary,risk_summary=:risk,due_at=:due,row_version=row_version+1,updated_at=now()
            where tenant_id=:tenant and coordination_case_id=:id and row_version=:version
            """).param("priority",request.priority().name()).param("target",request.targetUnit().trim()).param("requested_to",request.requestedTo()).param("summary",request.summary().trim()).param("risk",request.riskSummary().trim()).param("due",request.dueAt().atOffset(ZoneOffset.UTC)).param("tenant",identity.tenantId()).param("id",id).param("version",head.version()).update(); evidence(identity,request.patientId(),id,"EMERGENCY_COORDINATION_UPDATED"); complete(identity,"EMERGENCY_COORDINATION_UPDATE",key,id); return find(identity.tenantId(),id,request.patientId()); });
    }

    EmergencyCoordinationCaseWire transition(ClinicalIdentity identity, String key, UUID id, EmergencyCoordinationCaseTransitionRequestWire request) {
        return transactions.execute(status -> { begin(identity,"EMERGENCY_COORDINATION_TRANSITION",key,sha256(id+"|"+request.expectedRowVersion()+"|"+request.transition())); Head head=lock(identity,id,request.patientId(),request.encounterId(),request.facilityId()); requireVersion(head,request.expectedRowVersion()); if(request.transition()==EmergencyCoordinationCaseTransitionRequestWire.TransitionValue.ACKNOWLEDGE) { if(!"OPEN".equals(head.status())) throw state("Only an open case can be acknowledged"); if(head.requestedTo()!=null&&!head.requestedTo().equals(identity.userId())) throw new EmergencyCoordinationException("EMERGENCY_COORDINATION_RECEIVER_REQUIRED",403,"Only the designated receiver can acknowledge this case"); if(!"CONSULTATION".equals(head.caseType())&&head.requestedBy().equals(identity.userId())) throw new EmergencyCoordinationException("EMERGENCY_COORDINATION_SELF_ACK_FORBIDDEN",409,"Handoff and transfer require a different receiver"); jdbc.sql("update emergency_coordination_case set status='ACKNOWLEDGED',acknowledged_by=:actor,acknowledged_at=now(),row_version=row_version+1,updated_at=now() where tenant_id=:tenant and coordination_case_id=:id and row_version=:version").param("actor",identity.userId()).param("tenant",identity.tenantId()).param("id",id).param("version",head.version()).update(); } else { if(!"ACKNOWLEDGED".equals(head.status())) throw state("A case must be acknowledged before completion"); jdbc.sql("update emergency_coordination_case set status='COMPLETED',completed_by=:actor,completed_at=now(),row_version=row_version+1,updated_at=now() where tenant_id=:tenant and coordination_case_id=:id and row_version=:version").param("actor",identity.userId()).param("tenant",identity.tenantId()).param("id",id).param("version",head.version()).update(); } evidence(identity,request.patientId(),id,"EMERGENCY_COORDINATION_"+request.transition().name()); complete(identity,"EMERGENCY_COORDINATION_TRANSITION",key,id); return find(identity.tenantId(),id,request.patientId()); });
    }

    EmergencyCoordinationCaseWire voidCase(ClinicalIdentity identity,String key,UUID id,EmergencyCoordinationCaseVoidRequestWire request) {
        String reason=text(request.reason(),4,"reason"); return transactions.execute(status->{ begin(identity,"EMERGENCY_COORDINATION_VOID",key,sha256(id+"|"+request.expectedRowVersion()+"|"+reason)); Head head=lock(identity,id,request.patientId(),request.encounterId(),request.facilityId()); requireVersion(head,request.expectedRowVersion()); if(Set.of("COMPLETED","VOIDED").contains(head.status())) throw state("Completed or voided coordination cases cannot be deleted"); jdbc.sql("update emergency_coordination_case set status='VOIDED',voided_by=:actor,voided_at=now(),void_reason=:reason,row_version=row_version+1,updated_at=now() where tenant_id=:tenant and coordination_case_id=:id and row_version=:version").param("actor",identity.userId()).param("reason",reason).param("tenant",identity.tenantId()).param("id",id).param("version",head.version()).update(); evidence(identity,request.patientId(),id,"EMERGENCY_COORDINATION_VOIDED"); complete(identity,"EMERGENCY_COORDINATION_VOID",key,id); return find(identity.tenantId(),id,request.patientId()); });
    }

    List<EmergencyCoordinationCaseWire> list(ClinicalIdentity identity,UUID patientId){ return jdbc.sql("select coordination_case_id from emergency_coordination_case where tenant_id=:tenant and patient_id=:patient order by due_at,created_at desc limit 200").param("tenant",identity.tenantId()).param("patient",patientId).query(UUID.class).list().stream().map(id->find(identity.tenantId(),id,patientId)).toList(); }
    private EmergencyCoordinationCaseWire find(UUID tenant,UUID id,UUID patient){ return jdbc.sql("""
        select coordination_case_id,patient_id,encounter_id,facility_id,case_type,priority,target_unit,requested_to,summary,risk_summary,due_at,status,requested_by,acknowledged_by,acknowledged_at,completed_by,completed_at,voided_by,voided_at,void_reason,row_version from emergency_coordination_case where tenant_id=:tenant and coordination_case_id=:id and patient_id=:patient
        """).param("tenant",tenant).param("id",id).param("patient",patient).query((rs,row)->new EmergencyCoordinationCaseWire(rs.getObject("coordination_case_id",UUID.class),rs.getObject("patient_id",UUID.class),rs.getObject("encounter_id",UUID.class),rs.getObject("facility_id",UUID.class),EmergencyCoordinationCaseWire.CaseTypeValue.valueOf(rs.getString("case_type")),EmergencyCoordinationCaseWire.PriorityValue.valueOf(rs.getString("priority")),rs.getString("target_unit"),rs.getObject("requested_to",UUID.class),rs.getString("summary"),rs.getString("risk_summary"),rs.getObject("due_at",OffsetDateTime.class).toInstant(),EmergencyCoordinationCaseWire.StatusValue.valueOf(rs.getString("status")),rs.getObject("requested_by",UUID.class),rs.getObject("acknowledged_by",UUID.class),instant(rs,"acknowledged_at"),rs.getObject("completed_by",UUID.class),instant(rs,"completed_at"),rs.getObject("voided_by",UUID.class),instant(rs,"voided_at"),rs.getString("void_reason"),rs.getLong("row_version"))).optional().orElseThrow(EmergencyCoordinationService::contextDenied); }
    private static Instant instant(java.sql.ResultSet rs,String column) throws java.sql.SQLException { OffsetDateTime value=rs.getObject(column,OffsetDateTime.class); return value==null?null:value.toInstant(); }
    private Head lock(ClinicalIdentity identity,UUID id,UUID patient,UUID encounter,UUID facility){ return jdbc.sql("select status,case_type,requested_by,requested_to,row_version from emergency_coordination_case where tenant_id=:tenant and coordination_case_id=:id and patient_id=:patient and encounter_id=:encounter and facility_id=:facility for update").param("tenant",identity.tenantId()).param("id",id).param("patient",patient).param("encounter",encounter).param("facility",facility).query((rs,row)->new Head(rs.getString("status"),rs.getString("case_type"),rs.getObject("requested_by",UUID.class),rs.getObject("requested_to",UUID.class),rs.getLong("row_version"))).optional().orElseThrow(EmergencyCoordinationService::contextDenied); }
    private void requireEncounter(UUID tenant,UUID patient,UUID encounter,UUID facility){ long count=jdbc.sql("select count(*) from encounter where tenant_id=:tenant and patient_id=:patient and encounter_id=:encounter and facility_id=:facility and encounter_type='EMERGENCY' and status='IN_PROGRESS'").param("tenant",tenant).param("patient",patient).param("encounter",encounter).param("facility",facility).query(Long.class).single(); if(count!=1) throw contextDenied(); }
    private void requireUser(UUID tenant,UUID user){ if(user==null)return; long count=jdbc.sql("select count(*) from app_user where tenant_id=:tenant and user_id=:user and status='ACTIVE'").param("tenant",tenant).param("user",user).query(Long.class).single(); if(count!=1)throw contextDenied(); }
    private static void validate(UUID patient,UUID encounter,UUID facility,Object type,Object priority,String target,String summary,String risk,Instant due){ if(patient==null||encounter==null||facility==null||type==null||priority==null||due==null)throw invalid("Required emergency coordination fields are missing"); text(target,2,"target_unit");text(summary,2,"summary");text(risk,2,"risk_summary"); }
    private static void requireVersion(Head head,Long expected){ if(expected==null||head.version()!=expected)throw new EmergencyCoordinationException("EMERGENCY_COORDINATION_VERSION_CONFLICT",409,"The coordination case changed; reload before retrying"); }
    private void begin(ClinicalIdentity identity,String scope,String key,String hash){ if(key==null||key.isBlank()||key.length()>128)throw invalid("A valid Idempotency-Key is required"); int inserted=jdbc.sql("insert into idempotency_record(tenant_id,command_scope,idempotency_key,request_hash,state,trace_id,expires_at) values (:tenant,:scope,:key,:hash,'IN_PROGRESS',:trace,now()+interval '24 hours') on conflict (tenant_id,command_scope,idempotency_key) do nothing").param("tenant",identity.tenantId()).param("scope",scope).param("key",key).param("hash",hash).param("trace",UUID.randomUUID().toString()).update(); if(inserted!=1)throw new EmergencyCoordinationException("IDEMPOTENCY_REPLAY",409,"This command key was already used"); }
    private void complete(ClinicalIdentity identity,String scope,String key,UUID id){ jdbc.sql("update idempotency_record set state='SUCCEEDED',response_status=200,response_ref=jsonb_build_object('resource_id',:id) where tenant_id=:tenant and command_scope=:scope and idempotency_key=:key").param("id",id).param("tenant",identity.tenantId()).param("scope",scope).param("key",key).update(); }
    private void evidence(ClinicalIdentity identity,UUID patient,UUID id,String action){ jdbc.sql("select tenant_id from tenant where tenant_id=:tenant for update").param("tenant",identity.tenantId()).query(UUID.class).single();UUID audit=UUID.randomUUID();String trace=UUID.randomUUID().toString();String previous=jdbc.sql("select event_hash from audit_event where tenant_id=:tenant order by occurred_at desc,audit_event_id desc limit 1").param("tenant",identity.tenantId()).query(String.class).optional().orElse(null);String hash=sha256(identity.tenantId()+"|"+audit+"|"+action+"|"+id+"|"+trace+"|"+(previous==null?"GENESIS":previous));jdbc.sql("insert into audit_event(tenant_id,audit_event_id,occurred_at,actor_user_id,action_code,resource_type,resource_id,patient_ref_hash,trace_id,previous_hash,event_hash) values (:tenant,:audit,now(),:actor,:action,'EMERGENCY_COORDINATION',:id,:patient,:trace,:previous,:hash)").param("tenant",identity.tenantId()).param("audit",audit).param("actor",identity.userId()).param("action",action).param("id",id).param("patient",sha256(identity.tenantId()+"|"+patient)).param("trace",trace).param("previous",previous).param("hash",hash).update();jdbc.sql("insert into outbox_event(tenant_id,event_id,aggregate_type,aggregate_id,aggregate_version,event_type,schema_version,payload) values (:tenant,:event,'EMERGENCY_COORDINATION',:aggregate,1,:event_type,1,jsonb_build_object('resource_id',:aggregate,'action',:action))").param("tenant",identity.tenantId()).param("event",UUID.randomUUID()).param("aggregate",id).param("event_type",action).param("action",action).update(); }
    private static String text(String value,int min,String field){ if(value==null||value.trim().length()<min)throw invalid(field+" is required");return value.trim(); }
    private static EmergencyCoordinationException invalid(String message){return new EmergencyCoordinationException("EMERGENCY_COORDINATION_REQUEST_INVALID",400,message);} private static EmergencyCoordinationException state(String message){return new EmergencyCoordinationException("EMERGENCY_COORDINATION_STATE_INVALID",409,message);} static EmergencyCoordinationException contextDenied(){return new EmergencyCoordinationException("CONTEXT_NOT_PERMITTED",403,"The requested emergency coordination context is not permitted");}
    private static String sha256(String value){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8)));}catch(NoSuchAlgorithmException impossible){throw new IllegalStateException(impossible);}}
    private record Head(String status,String caseType,UUID requestedBy,UUID requestedTo,long version){}
}
