package org.openemr2026.emergency;

import jakarta.servlet.http.HttpServletRequest; import java.util.List; import java.util.UUID;
import org.openemr2026.contracts.*; import org.openemr2026.security.*;
import org.springframework.http.CacheControl; import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

@RestController @RequestMapping("/api/v1")
final class EmergencyCoordinationController {
    private final ClinicalCommandSecurity security; private final EmergencyCoordinationService service;
    EmergencyCoordinationController(ClinicalCommandSecurity security, EmergencyCoordinationService service) { this.security = security; this.service = service; }
    @GetMapping("/emergency-coordination-cases") ResponseEntity<List<EmergencyCoordinationCaseWire>> list(HttpServletRequest request, @RequestParam("patient_id") UUID patientId, @RequestHeader("X-Organization-Context") UUID organizationId, @RequestHeader("X-Facility-Context") UUID facilityId, @RequestHeader("X-Patient-Context") UUID patientContextId) { if (!patientId.equals(patientContextId)) throw EmergencyCoordinationService.contextDenied(); ClinicalIdentity identity = security.authorize(request, organizationId, facilityId, patientId, null); return ResponseEntity.ok().cacheControl(CacheControl.noStore()).body(service.list(identity, patientId)); }
    @PostMapping("/emergency-coordination-cases") ResponseEntity<EmergencyCoordinationCaseWire> create(HttpServletRequest request, @RequestHeader("Idempotency-Key") String key, @RequestBody EmergencyCoordinationCaseCreateRequestWire command) { ClinicalIdentity identity = security.authorize(request, command.organizationId(), command.facilityId(), command.patientId(), command.encounterId()); return ResponseEntity.status(201).cacheControl(CacheControl.noStore()).body(service.create(identity, key, command)); }
    @PutMapping("/emergency-coordination-cases/{coordination_case_id}") ResponseEntity<EmergencyCoordinationCaseWire> update(HttpServletRequest request, @PathVariable("coordination_case_id") UUID id, @RequestHeader("Idempotency-Key") String key, @RequestBody EmergencyCoordinationCaseUpdateRequestWire command) { ClinicalIdentity identity = security.authorize(request, command.organizationId(), command.facilityId(), command.patientId(), command.encounterId()); return ResponseEntity.ok().cacheControl(CacheControl.noStore()).body(service.update(identity, key, id, command)); }
    @PostMapping("/emergency-coordination-cases/{coordination_case_id}/transitions") ResponseEntity<EmergencyCoordinationCaseWire> transition(HttpServletRequest request, @PathVariable("coordination_case_id") UUID id, @RequestHeader("Idempotency-Key") String key, @RequestBody EmergencyCoordinationCaseTransitionRequestWire command) { ClinicalIdentity identity = security.authorize(request, command.organizationId(), command.facilityId(), command.patientId(), command.encounterId()); return ResponseEntity.ok().cacheControl(CacheControl.noStore()).body(service.transition(identity, key, id, command)); }
    @PostMapping("/emergency-coordination-cases/{coordination_case_id}/voids") ResponseEntity<EmergencyCoordinationCaseWire> voidCase(HttpServletRequest request, @PathVariable("coordination_case_id") UUID id, @RequestHeader("Idempotency-Key") String key, @RequestBody EmergencyCoordinationCaseVoidRequestWire command) { ClinicalIdentity identity = security.authorize(request, command.organizationId(), command.facilityId(), command.patientId(), command.encounterId()); return ResponseEntity.ok().cacheControl(CacheControl.noStore()).body(service.voidCase(identity, key, id, command)); }
}
