package org.openemr2026.emergency;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import java.time.*; import java.util.*;
import org.openemr2026.contracts.*; import org.openemr2026.security.ClinicalIdentity;
import org.junit.jupiter.api.Test; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.jdbc.core.simple.JdbcClient; import org.springframework.test.context.ActiveProfiles;

@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT) @ActiveProfiles("dev-synthetic")
final class EmergencyCoordinationApiTest {
    private static final UUID TENANT=UUID.fromString("018f0000-0000-7000-8000-00000000aa01"), ORGANIZATION=UUID.fromString("018f0000-0000-7000-8000-00000000aa02"), FACILITY=UUID.fromString("018f0000-0000-7000-8000-00000000aa03"), REQUESTER=UUID.fromString("018f0000-0000-7000-8000-00000000aa04"), RECEIVER=UUID.fromString("018f0000-0000-7000-8000-00000000aa06"), ROLE=UUID.fromString("018f0000-0000-7000-8000-00000000aa05");
    @Autowired EmergencyCoordinationService service; @Autowired JdbcClient jdbc;
    private ClinicalIdentity requester(){return new ClinicalIdentity(TENANT,REQUESTER,List.of(ROLE));} private ClinicalIdentity receiver(){return new ClinicalIdentity(TENANT,RECEIVER,List.of(ROLE));}
    private Context seed(){UUID patient=UUID.randomUUID(),encounter=UUID.randomUUID();jdbc.sql("insert into patient(tenant_id,patient_id,display_name,sex_code,birth_date,status) values (:tenant,:patient,'急诊协同患者','M',:birth,'ACTIVE')").param("tenant",TENANT).param("patient",patient).param("birth",LocalDate.of(1972,1,2)).update();jdbc.sql("insert into encounter(tenant_id,encounter_id,patient_id,organization_id,facility_id,encounter_type,status,started_at,source_system,source_key) values (:tenant,:encounter,:patient,:organization,:facility,'EMERGENCY','IN_PROGRESS',now(),'TEST',:key)").param("tenant",TENANT).param("encounter",encounter).param("patient",patient).param("organization",ORGANIZATION).param("facility",FACILITY).param("key",encounter.toString()).update();return new Context(patient,encounter);}
    private EmergencyCoordinationCaseWire create(Context c,EmergencyCoordinationCaseCreateRequestWire.CaseTypeValue type){return service.create(requester(),"coord-"+UUID.randomUUID(),new EmergencyCoordinationCaseCreateRequestWire(ORGANIZATION,FACILITY,c.patient(),c.encounter(),type,EmergencyCoordinationCaseCreateRequestWire.PriorityValue.URGENT,"心内科CCU",RECEIVER,"急性胸痛待协同","未回肌钙蛋白，持续心电监护",Instant.now().plusSeconds(1800)));}

    @Test void consultationHandoffAndTransferUseEmergencyPatientContextAndRealLifecycle(){Context c=seed();EmergencyCoordinationCaseWire item=create(c,EmergencyCoordinationCaseCreateRequestWire.CaseTypeValue.HANDOFF);assertThat(item.status()).isEqualTo(EmergencyCoordinationCaseWire.StatusValue.OPEN);EmergencyCoordinationCaseWire acknowledged=service.transition(receiver(),"ack-"+UUID.randomUUID(),item.coordinationCaseId(),new EmergencyCoordinationCaseTransitionRequestWire(ORGANIZATION,FACILITY,c.patient(),c.encounter(),item.rowVersion(),EmergencyCoordinationCaseTransitionRequestWire.TransitionValue.ACKNOWLEDGE));assertThat(acknowledged.acknowledgedBy()).isEqualTo(RECEIVER);EmergencyCoordinationCaseWire completed=service.transition(receiver(),"done-"+UUID.randomUUID(),item.coordinationCaseId(),new EmergencyCoordinationCaseTransitionRequestWire(ORGANIZATION,FACILITY,c.patient(),c.encounter(),acknowledged.rowVersion(),EmergencyCoordinationCaseTransitionRequestWire.TransitionValue.COMPLETE));assertThat(completed.status()).isEqualTo(EmergencyCoordinationCaseWire.StatusValue.COMPLETED);}
    @Test void requesterCannotSelfAcknowledgeHandoff(){Context c=seed();EmergencyCoordinationCaseWire item=create(c,EmergencyCoordinationCaseCreateRequestWire.CaseTypeValue.HANDOFF);assertThatThrownBy(()->service.transition(requester(),"self-"+UUID.randomUUID(),item.coordinationCaseId(),new EmergencyCoordinationCaseTransitionRequestWire(ORGANIZATION,FACILITY,c.patient(),c.encounter(),item.rowVersion(),EmergencyCoordinationCaseTransitionRequestWire.TransitionValue.ACKNOWLEDGE))).isInstanceOf(EmergencyCoordinationException.class);}
    @Test void openCaseCanBeEditedAndVoided(){Context c=seed();EmergencyCoordinationCaseWire item=create(c,EmergencyCoordinationCaseCreateRequestWire.CaseTypeValue.CONSULTATION);EmergencyCoordinationCaseWire updated=service.update(requester(),"update-"+UUID.randomUUID(),item.coordinationCaseId(),new EmergencyCoordinationCaseUpdateRequestWire(ORGANIZATION,FACILITY,c.patient(),c.encounter(),item.rowVersion(),EmergencyCoordinationCaseUpdateRequestWire.PriorityValue.IMMEDIATE,"心内科胸痛中心",RECEIVER,"持续胸痛需立即会诊","心电图动态改变",Instant.now().plusSeconds(600)));assertThat(updated.priority()).isEqualTo(EmergencyCoordinationCaseWire.PriorityValue.IMMEDIATE);EmergencyCoordinationCaseWire voided=service.voidCase(requester(),"void-"+UUID.randomUUID(),item.coordinationCaseId(),new EmergencyCoordinationCaseVoidRequestWire(ORGANIZATION,FACILITY,c.patient(),c.encounter(),updated.rowVersion(),"重复发起会诊"));assertThat(voided.status()).isEqualTo(EmergencyCoordinationCaseWire.StatusValue.VOIDED);assertThat(service.list(requester(),c.patient())).extracting(EmergencyCoordinationCaseWire::coordinationCaseId).contains(item.coordinationCaseId());}
    private record Context(UUID patient,UUID encounter){}
}
