import { generatedRouteContract } from '../generated/route-contract';

export type PrimaryDomain = typeof generatedRouteContract.routes[number]['primary_domain'];
export type ClinicalRouteDefinition = typeof generatedRouteContract.routes[number];

export const routeRegistry: readonly ClinicalRouteDefinition[] = generatedRouteContract.routes;
export const routeById: ReadonlyMap<string, ClinicalRouteDefinition> = new Map(
  routeRegistry.map((route) => [route.route_id, route] as const),
);

export const nativeVueRouteIds: ReadonlySet<string> = new Set([
  'clinical',
  'admin',
  'admission-bed',
  'outpatient',
  'opd-record',
  'record',
  'record-qc',
  'record-sign',
  'record-sources',
  'inpatient',
  'inpatient-overview',
  'inpatient-course',
  'inpatient-doc-editor',
  'inpatient-doc-qc',
  'inpatient-doc-versions',
  'inpatient-discharge',
  'record-versions',
  'record-diff',
  'record-editor',
  'lis-report',
  'pacs-viewer',
  'archive-assets',
  'archive-borrow',
  'archive-catalog',
  'archive-integrity',
  'asset-detail',
  'opd-orders',
  'ip-orders',
  'opd-diagnosis',
  'clinical-tasks',
  'opd-results',
  'ip-results',
  'ip-consult',
  'ip-pathway',
  'admin-org',
  'admin-users',
  'admin-permissions',
  'admin-templates',
  'admin-dictionaries',
  'admin-audit',
  'capability-pack',
  'integration',
  'migration',
  'models',
  'agent-catalog',
  'skill-catalog',
  'tool-catalog',
  'model-evaluation',
  'aiops',
  'data-quality',
  'cohort-builder',
  'research-dataset',
  'opensource',
  'emergency-access',
  'patient-registry',
  'patient-merge',
  'patient-timeline',
  'appointment-registration',
  'emergency',
  'er-triage',
  'er-observation',
  'er-record',
  'er-nursing',
  'er-handoff',
  'er-patient-overview',
  'er-clinical-timeline',
  'er-safety-gates',
  'er-transfer-readiness',
  'er-evidence-ledger',
  'opd-consult',
  'billing',
  'outpatient-pharmacy',
  'inpatient-pharmacy',
  'lab-workbench',
  'imaging-workbench',
  'transfusion',
  'surgery-schedule',
  'care-operations',
  'ward',
  'infection-events',
  'quality-rating',
  'credentials',
  'specialty-center',
  'obgyn-record',
  'reproductive-record',
  'pediatrics-record',
  'neonatal-record',
  'mental-record',
  'ophthalmology-record',
  'ent-record',
  'dental-record',
  'dermatology-record',
  'tcm-record',
  'obgyn-workbench',
  'reproductive-workbench',
  'pediatrics-workbench',
  'neonatal-workbench',
  'mental-workbench',
  'ophthalmology-workbench',
  'ent-workbench',
  'dental-workbench',
  'dermatology-workbench',
  'tcm-workbench',
  'obgyn-treatment',
  'obgyn-evidence',
  'obgyn-followup',
  'obgyn-qc',
  'reproductive-treatment',
  'reproductive-followup',
  'pediatrics-care',
  'pediatrics-followup',
  'neonatal-care',
  'neonatal-evidence',
  'mental-care',
  'mental-followup',
  'ophthalmology-treatment',
  'ophthalmology-followup',
  'ent-care',
  'dental-treatment',
  'dermatology-treatment',
  'dermatology-followup',
  'tcm-treatment',
  'tcm-evidence',
  'tcm-qc',
  'reproductive-qc',
  'pediatrics-qc',
  'neonatal-qc',
  'mental-qc',
  'ophthalmology-qc',
  'ent-qc',
  'dental-qc',
  'dermatology-qc',
  'neonatal-followup',
  'ent-followup',
  'dental-followup',
  'tcm-followup',
  'obgyn-care',
  'reproductive-care',
  'ophthalmology-care',
  'dental-care',
  'dermatology-care',
  'tcm-care',
  'reproductive-evidence',
  'pediatrics-evidence',
  'mental-evidence',
  'ophthalmology-evidence',
  'ent-evidence',
  'dental-evidence',
  'dermatology-evidence',
  'pediatrics-treatment',
  'neonatal-treatment',
  'mental-treatment',
  'ent-treatment',
  'ai-action-review',
  'ai-reminder-detail',
  'ai-assistant',
  'integration-mapping',
  'specialty-coverage',
  'admin-roles',
  'admin-auth',
  'admin-jobs',
  'admin-master-data',
  'admin-parameters',
  'agent',
  'agent-compose',
  'agent-context',
  'agent-evals',
  'ai-assistant-policy',
  'ai-capture',
  'anesthesia-workbench',
  'archive-preservation',
  'archive-scan',
  'backup',
  'config-release',
  'config-upgrade',
  'data-center',
  'department-qc',
  'device-monitoring',
  'devices',
  'form-designer',
  'install',
  'integration-connectors',
  'integration-messages',
  'knowledge-center',
  'pathway-graph',
  'pathway-review',
  'pathway-versions',
  'login-context',
  'model-connection',
  'model-routing',
  'opd-followup',
  'operations',
  'pathology-workbench',
  'quality-center',
  'release-gates',
  'research',
  'research-stats',
  'rule-center',
  'scope-designer',
  'therapy-workbench',
  'unified-home',
  'workflow',
]);

const specialtyScopeByPrefix: Readonly<Record<string, string>> = Object.freeze({
  dental: 'DENTAL', dermatology: 'DERMATOLOGY', ent: 'ENT', mental: 'MENTAL_HEALTH',
  neonatal: 'NEONATAL', obgyn: 'OBGYN', ophthalmology: 'OPHTHALMOLOGY',
  pediatrics: 'PEDIATRICS', reproductive: 'REPRODUCTIVE_MEDICINE', tcm: 'TCM',
});

export const specialtyGuardRouteIds: ReadonlySet<string> = new Set(routeRegistry
  .map((route) => route.route_id)
  .filter((routeId) => routeId === 'specialty-center' || Object.keys(specialtyScopeByPrefix).some((prefix) => routeId.startsWith(`${prefix}-`))));

export function specialtyScopeForRoute(routeId: string): string | null {
  if (routeId === 'specialty-center') return null;
  const prefix = routeId.split('-', 1)[0];
  return specialtyScopeByPrefix[prefix] ?? null;
}

export type PrimaryNavigationId = 'outpatient' | 'inpatient' | 'emergency' | 'record' | 'quality' | 'data' | 'configuration';

export function primaryNavigationId(routeId: string): PrimaryNavigationId {
  const definition = routeById.get(routeId);
  if (definition?.primary_domain === 'RECORD') return 'record';
  if (definition?.primary_domain === 'QUALITY') return 'quality';
  if (definition?.primary_domain === 'DATA' || definition?.primary_domain === 'COLLABORATION') return 'data';
  if (['AI', 'CONFIG', 'ADMIN'].includes(definition?.primary_domain ?? '')) return 'configuration';
  if (/^(inpatient|ip-|admission|ward)/.test(routeId)) return 'inpatient';
  if (/^(emergency|er-)/.test(routeId)) return 'emergency';
  return 'outpatient';
}
