<script setup lang="ts">
import { useQuery } from '@tanstack/vue-query';
import { computed, ref } from 'vue';
import type { MedicalRecordAssetWire } from '../../generated/contracts';
import { issueMedicalRecordAssetLease, listMedicalRecordAssets, updateMedicalRecordAsset, verifyMedicalRecordAssetStorage } from '../../api/records';
import BusinessActionDialog from '../components/BusinessActionDialog.vue';
import ClinicalPageState from '../components/ClinicalPageState.vue';
import { toClinicalIssue } from '../clinical-error';

const query = useQuery({ queryKey: ['clinical','medical-record-assets','preservation'], queryFn: async () => { const lease = await issueMedicalRecordAssetLease(); return { lease, assets: await listMedicalRecordAssets(lease) }; }, retry: false, staleTime: 0, gcTime: 0 });
const issue = computed(() => query.error.value ? toClinicalIssue(query.error.value) : null);
const assets = computed(() => (query.data.value?.assets ?? []).filter((item) => item.status !== 'RETIRED'));
const busy = ref(false); const notice = ref(''); const planTarget = ref<MedicalRecordAssetWire|null>(null); const planAction = ref<'save'|'delete'>('save'); const planYears = ref(15); const restoreTarget = ref<MedicalRecordAssetWire|null>(null); const sealTarget = ref<MedicalRecordAssetWire|null>(null); const strategyOpen = ref(false); const selectedAssetId = ref('');
const scheduled = computed(() => assets.value.filter((x) => x.preservation_status === 'SCHEDULED').length);
const sealed = computed(() => assets.value.filter((x) => x.preservation_status === 'SEALED').length);
const verified = computed(() => assets.value.filter((x) => x.preservation_status === 'VERIFIED').length);
const selectedAsset = computed(() => assets.value.find((asset) => asset.medical_record_asset_id === selectedAssetId.value) ?? assets.value.find((asset) => asset.preservation_status === 'SEALED') ?? assets.value[0] ?? null);
const formatRisk = computed(() => assets.value.filter((asset) => /tiff|octet-stream|vendor|legacy/i.test(`${asset.media_type} ${asset.source_system}`)).length);
const frozen = computed(() => assets.value.filter((asset) => asset.object_lock_status === 'LOCKED').length);
function openPlan(asset: MedicalRecordAssetWire) { planTarget.value = asset; planAction.value = 'save'; planYears.value = asset.retention_years; }
function openDelete(asset: MedicalRecordAssetWire) { planTarget.value = asset; planAction.value = 'delete'; planYears.value = asset.retention_years; }
async function changePlan() {
  const data=query.data.value, asset=planTarget.value; if(!data||!asset||busy.value)return; busy.value=true; notice.value='';
  const nextStatus = planAction.value === 'delete' ? 'NOT_SCHEDULED' : asset.preservation_status === 'NOT_SCHEDULED' ? 'SCHEDULED' : asset.preservation_status;
  try { await updateMedicalRecordAsset(data.lease, asset, { display_name:asset.display_name,media_type:asset.media_type,page_count:asset.page_count,source_system:asset.source_system,custody_location:asset.custody_location,cda_status:asset.cda_status,scan_status:asset.scan_status,preservation_status:nextStatus,retention_years:planYears.value }); notice.value=planAction.value==='delete'?'长期保存排期已取消，资产本身与验真证据保留。':'长期保存计划已更新，将影响封包与恢复验证队列。'; planTarget.value=null; await query.refetch(); } catch(error){const next=toClinicalIssue(error);notice.value=`${next.code}：${next.message}`;} finally{busy.value=false;}
}
async function sealAsset() { const data=query.data.value,asset=sealTarget.value;if(!data||!asset||busy.value)return;busy.value=true;try{const updated=await updateMedicalRecordAsset(data.lease,asset,{display_name:asset.display_name,media_type:asset.media_type,page_count:asset.page_count,source_system:asset.source_system,custody_location:asset.custody_location,cda_status:asset.cda_status,scan_status:asset.scan_status,preservation_status:'SEALED',retention_years:asset.retention_years});notice.value=updated.storage_provider==='FILESYSTEM_DEV'?'开发文件存储已写入只读建议锁和数据库保留期门禁；这不等于生产 WORM。':`${updated.storage_provider} 已返回对象锁证据，保留期只能延长。`;sealTarget.value=null;await query.refetch();}catch(error){const next=toClinicalIssue(error);notice.value=`${next.code}：${next.message}`;}finally{busy.value=false;} }
async function restoreVerify(){const data=query.data.value,asset=restoreTarget.value;if(!data||!asset)return;busy.value=true;try{const event=await verifyMedicalRecordAssetStorage(data.lease,asset);notice.value=event.result==='VERIFIED'?`服务端已从 ${asset.storage_provider} 重读实际字节，恢复验证通过。`:`${asset.storage_provider} 重读哈希不一致，已标记失败。`;restoreTarget.value=null;await query.refetch();}catch(error){const next=toClinicalIssue(error);notice.value=`${next.code}：${next.message}`;}finally{busy.value=false;}}
function preservationLabel(value:string){return({NOT_SCHEDULED:'未纳入',SCHEDULED:'已排期',SEALED:'已封包',VERIFIED:'恢复验证通过'}as Record<string,string>)[value]||value;}
function storageLabel(asset:MedicalRecordAssetWire){if(asset.storage_provider==='FILESYSTEM_DEV')return asset.object_lock_status==='LOCKED'?'开发文件存储 + 建议锁':'开发文件存储';return asset.object_lock_status==='LOCKED'?`${asset.storage_provider} + Object Lock`:asset.storage_provider;}
</script>

<template>
  <section data-page-root class="content vue-native-page archive-prototype-page">
    <div class="page-head"><div class="page-title"><h1>病案长期保存与恢复验证</h1><p>保管期限、介质迁移、格式风险、周期验真、法律冻结和隔离恢复</p></div><div class="head-actions"><button class="btn" @click="strategyOpen = true">保存策略 v3.1</button><button class="btn primary" :disabled="!selectedAsset || !['SEALED','VERIFIED'].includes(selectedAsset.preservation_status)" @click="restoreTarget = selectedAsset">发起恢复抽检</button></div></div>
    <ClinicalPageState v-if="query.isPending.value" kind="loading" message="正在加载长期保存计划" />
    <ClinicalPageState v-else-if="issue" kind="error" :code="issue.code" :message="issue.message" @retry="query.refetch()" />
    <template v-else>
      <div v-if="notice" class="notice archive-notice">{{ notice }}</div>
      <div class="metric-grid"><div class="metric"><div class="name">长期保存病案</div><div class="value">{{ scheduled + sealed + verified }}</div><div class="trend">当前患者资产</div></div><div class="metric"><div class="name">本期验真</div><div class="value">{{ verified }}</div><div class="trend">恢复验证通过</div></div><div class="metric"><div class="name">格式风险</div><div class="value">{{ formatRisk }}</div><div class="trend">旧格式/私有格式</div></div><div class="metric"><div class="name">法律冻结</div><div class="value">{{ frozen }}</div><div class="trend">WORM 禁止缩短保留期</div></div></div>
      <div class="grid preservation-layout">
        <section class="card"><div class="card-head">保存分层与介质健康</div><div class="archive-table-wrap"><table class="table"><thead><tr><th>层级</th><th>对象</th><th>介质/副本</th><th>校验</th><th>状态</th></tr></thead><tbody><tr v-for="asset in assets" :key="asset.medical_record_asset_id" :class="{ 'prototype-row-active': selectedAsset?.medical_record_asset_id === asset.medical_record_asset_id }" @click="selectedAssetId = asset.medical_record_asset_id"><td><b>{{ asset.preservation_status === 'NOT_SCHEDULED' ? '待纳入' : asset.preservation_status === 'SCHEDULED' ? '温存储' : '冷归档' }}</b><small>{{ preservationLabel(asset.preservation_status) }}</small></td><td>{{ asset.display_name }}</td><td>{{ storageLabel(asset) }}</td><td>{{ asset.last_verified_at ? new Date(asset.last_verified_at).toLocaleDateString('zh-CN') : '待抽检' }}</td><td><span class="status" :class="asset.integrity_status === 'VERIFIED' ? 'green' : asset.integrity_status === 'FAILED' ? 'red' : 'amber'">{{ asset.integrity_status === 'VERIFIED' ? '正常' : asset.integrity_status === 'FAILED' ? '阻断' : '观察' }}</span></td></tr><tr v-if="!assets.length"><td colspan="5" class="prototype-empty">暂无可保存资产</td></tr></tbody></table></div><div class="card-body"><div class="notice rule"><div class="notice-title">格式迁移不覆盖原件</div>旧 TIFF/私有格式转换为长期格式时，原文件、转换工具版本、输入输出哈希和人工抽检结果共同保存。</div><div class="prototype-action-row" style="margin-top:12px"><button class="btn primary" :disabled="!selectedAsset || selectedAsset.preservation_status !== 'NOT_SCHEDULED'" @click="selectedAsset && openPlan(selectedAsset)">新建计划</button><button class="btn" :disabled="!selectedAsset || selectedAsset.preservation_status !== 'SCHEDULED'" @click="selectedAsset && openPlan(selectedAsset)">编辑</button><button class="btn" :disabled="!selectedAsset || selectedAsset.preservation_status !== 'SCHEDULED' || selectedAsset.integrity_status !== 'VERIFIED' || selectedAsset.storage_status === 'MISSING'" @click="sealTarget = selectedAsset">封包</button><button class="btn danger" :disabled="!selectedAsset || selectedAsset.preservation_status !== 'SCHEDULED'" @click="selectedAsset && openDelete(selectedAsset)">删除</button></div></div></section>
        <aside class="card"><div class="card-head">最近恢复抽检</div><div class="card-body"><div class="folder-row">抽检对象<span>{{ selectedAsset?.display_name ?? '未选择' }}</span></div><div class="folder-row">资产数量<span>{{ selectedAsset ? 1 : 0 }}</span></div><div class="folder-row">对象恢复<span>{{ selectedAsset?.storage_status === 'MISSING' ? '0 / 1' : '1 / 1' }}</span></div><div class="folder-row">哈希一致<span>{{ selectedAsset?.integrity_status === 'VERIFIED' ? '100%' : '待验证' }}</span></div><div class="folder-row">WORM 状态<span>{{ selectedAsset?.object_lock_status ?? '—' }}</span></div><div class="folder-row">保留到期<span>{{ selectedAsset?.worm_retain_until ? new Date(selectedAsset.worm_retain_until).toLocaleDateString('zh-CN') : '未锁定' }}</span></div><div class="folder-row">最后验真<span>{{ selectedAsset?.last_verified_at ? new Date(selectedAsset.last_verified_at).toLocaleString('zh-CN') : '—' }}</span></div><div class="folder-row">结论<span>{{ selectedAsset?.preservation_status === 'VERIFIED' ? '通过' : '待抽检' }}</span></div><button class="btn" style="width:100%;margin-top:12px" :disabled="!selectedAsset || !['SEALED','VERIFIED'].includes(selectedAsset.preservation_status)" @click="restoreTarget = selectedAsset">打开恢复差异报告</button></div></aside>
      </div>
    </template>
    <BusinessActionDialog :open="strategyOpen" title="保存策略 v3.1" description="展示目标策略与当前证据；是否达到生产 WORM 以 storage provider 和 object-lock evidence 为准。" eyebrow="长期保存 / 策略" confirm-label="已了解" @cancel="strategyOpen = false" @confirm="strategyOpen = false"><div class="folder-row">热/温存储目标<span>对象存储多副本</span></div><div class="folder-row">冷归档目标<span>WORM + 离线副本</span></div><div class="folder-row">开发文件存储<span>仅建议锁，不是合规 WORM</span></div><div class="folder-row">保留期限<span>只能延长，不能缩短</span></div><div class="folder-row">恢复验真<span>重读实际字节并复算 SHA-256</span></div></BusinessActionDialog>
    <BusinessActionDialog :open="Boolean(planTarget)" :title="planAction === 'delete' ? '删除长期保存计划' : planTarget?.preservation_status === 'NOT_SCHEDULED' ? '新建长期保存计划' : '编辑长期保存计划'" :description="planAction === 'delete' ? '仅取消排期，不删除资产与证据。' : '保管年限会影响后续封包和恢复抽检。'" eyebrow="长期保存 / 计划" :danger="planAction === 'delete'" :confirm-label="planAction === 'delete' ? '确认取消' : '保存计划'" :busy="busy" @cancel="planTarget = null" @confirm="changePlan"><p v-if="planAction === 'delete'" class="dialog-warning">只有“已排期”且未封包的计划可删除。</p><label v-else>保管年限<input v-model.number="planYears" type="number" min="1" max="100" /></label></BusinessActionDialog>
    <BusinessActionDialog :open="Boolean(sealTarget)" title="封包并启用 WORM" description="原始对象将设为只读，保留到期日只能延长不能缩短。" eyebrow="长期保存 / WORM" confirm-label="确认封包" :busy="busy" @cancel="sealTarget = null" @confirm="sealAsset"><p class="dialog-warning">{{ sealTarget?.display_name }} · {{ sealTarget?.retention_years }} 年。封包后不可作废或解锁。</p></BusinessActionDialog>
    <BusinessActionDialog :open="Boolean(restoreTarget)" title="抽样恢复验证" description="服务端从 WORM 对象重新读取实际字节并复算 SHA-256。" eyebrow="长期保存 / 恢复" confirm-label="执行重读比对" :busy="busy" @cancel="restoreTarget = null" @confirm="restoreVerify"><p class="dialog-warning">{{ restoreTarget?.display_name }} · {{ restoreTarget?.object_lock_status }}</p></BusinessActionDialog>
  </section>
</template>
