<script setup lang="ts">
import { useQuery } from '@tanstack/vue-query';
import { computed, reactive, ref } from 'vue';
import type { AuthorizationDecisionWire, AuthorizationPolicyCreateRequestWire, AuthorizationPolicyWire, EmergencyAccessGrantWire } from '../../generated/contracts';
import { clinicalContext, createAuthorizationPolicy, loadAuthorizationPolicies, loadEmergencyAccessForReview, publishAuthorizationPolicy, reviewEmergencyAccess, simulateAuthorization } from '../../clinical-api';
import ClinicalPageState from '../components/ClinicalPageState.vue';
import { toClinicalIssue } from '../clinical-error';

const query = useQuery({ queryKey: ['admin', 'authorization'], queryFn: async () => ({ policies: await loadAuthorizationPolicies(), grants: await loadEmergencyAccessForReview() }), retry: false, staleTime: 0, gcTime: 0 });
const issue = computed(() => query.error.value ? toClinicalIssue(query.error.value) : null);
const policies = computed(() => query.data.value?.policies ?? []); const grants = computed(() => query.data.value?.grants ?? []);
const busy = ref(''); const notice = ref(''); const decision = ref<AuthorizationDecisionWire | null>(null);
const form = reactive({ code: '', effect: 'ALLOW' as 'ALLOW' | 'DENY', role: 'CLINICIAN', resource: 'CLINICAL_CONTEXT', action: 'LEASE_ISSUE', relationshipRequired: true, purpose: 'DOCUMENT_DRAFT', priority: 500 });
const simulation = reactive({ userId: clinicalContext.userId, roleId: clinicalContext.roleId, patientId: clinicalContext.patientId, encounterId: clinicalContext.encounterId, purpose: 'DOCUMENT_DRAFT' });
const publishedCount = computed(() => policies.value.filter((p) => p.status === 'PUBLISHED').length);
const draftCount = computed(() => policies.value.filter((p) => p.status === 'DRAFT').length);
const pendingReviews = computed(() => grants.value.filter((g) => g.status !== 'REVIEWED').length);
function formatDate(value: string | null) { return value ? new Intl.DateTimeFormat('zh-CN', { dateStyle: 'medium', timeStyle: 'short', hour12: false }).format(new Date(value)) : '长期'; }

async function createPolicy() {
  if (busy.value || !form.code.trim()) return; busy.value = 'create'; notice.value = '';
  const input: AuthorizationPolicyCreateRequestWire = { policy_id: crypto.randomUUID(), policy_code: form.code.trim(), version_no: 1, effect: form.effect, subject_role_code: form.role.trim() || undefined, resource_type: form.resource, action_code: form.action, organization_id: clinicalContext.organizationId, facility_id: clinicalContext.facilityId, patient_relationship_required: form.relationshipRequired, relationship_types: form.relationshipRequired ? ['CARE_TEAM'] : [], resource_statuses: ['ACTIVE'], purpose_codes: form.purpose.trim() ? [form.purpose.trim()] : [], emergency_override_allowed: true, priority: form.priority, valid_from: new Date().toISOString() };
  try { await createAuthorizationPolicy(input); notice.value = '策略草案已生成，必须由另一安全管理员审批后才生效。'; form.code = ''; await query.refetch(); }
  catch (error) { const next = toClinicalIssue(error); notice.value = `${next.code}：${next.message}`; } finally { busy.value = ''; }
}
async function publish(policy: AuthorizationPolicyWire) { busy.value = policy.policy_id; notice.value = ''; try { await publishAuthorizationPolicy(policy); notice.value = '策略已经独立审批并发布。'; await query.refetch(); } catch (error) { const next = toClinicalIssue(error); notice.value = `${next.code}：${next.message}`; } finally { busy.value = ''; } }
async function simulate() { busy.value = 'simulate'; notice.value = ''; decision.value = null; try { decision.value = await simulateAuthorization({ target_user_id: simulation.userId, target_role_assignment_ids: [simulation.roleId], resource_type: form.resource, action_code: form.action, organization_id: clinicalContext.organizationId, facility_id: clinicalContext.facilityId, patient_id: simulation.patientId, encounter_id: simulation.encounterId, purpose_code: simulation.purpose, resource_status: 'ACTIVE' }); } catch (error) { const next = toClinicalIssue(error); notice.value = `${next.code}：${next.message}`; } finally { busy.value = ''; } }
async function review(grant: EmergencyAccessGrantWire, outcome: 'APPROPRIATE' | 'INAPPROPRIATE' | 'ESCALATED') { busy.value = grant.emergency_access_grant_id; notice.value = ''; try { await reviewEmergencyAccess(grant, outcome, '安全管理员事后复核紧急访问范围与时限'); notice.value = '紧急访问已完成独立复核。'; await query.refetch(); } catch (error) { const next = toClinicalIssue(error); notice.value = `${next.code}：${next.message}`; } finally { busy.value = ''; } }
</script>

<template>
  <section data-page-root class="content admin-content vue-native-page"><div class="page-heading admin-heading"><div><p class="eyebrow">配置中心 / 权限策略</p><h1>权限策略与访问模拟</h1><p>使用“主体—资源—动作—范围—条件—效果”策略。显式拒绝优先，创建者不能自批，模拟与运行时使用同一决策器。</p></div><div class="toolbar-actions"><RouterLink class="button secondary" to="/admin-users">人员管理</RouterLink><RouterLink class="button secondary" to="/emergency-access">紧急访问</RouterLink></div></div>
    <ClinicalPageState v-if="query.isPending.value" kind="loading" message="正在读取策略版本和紧急访问复核队列" /><ClinicalPageState v-else-if="issue" kind="error" :code="issue.code" :message="issue.message" @retry="query.refetch()" />
    <template v-else><section class="admin-metrics auth-metrics"><article><span>已发布</span><strong>{{ publishedCount }}</strong><small>运行时生效</small></article><article><span>待审批</span><strong>{{ draftCount }}</strong><small>需独立安全管理员</small></article><article><span>紧急复核</span><strong>{{ pendingReviews }}</strong><small>未关闭记录</small></article><article><span>决策结果</span><strong class="auth-decision" :class="decision?.allowed ? 'allowed' : 'denied'">{{ decision ? (decision.allowed ? '允许' : '拒绝') : '未模拟' }}</strong><small>{{ decision?.reason_code || '运行前可预演' }}</small></article></section><p v-if="notice" class="admin-notice" role="status">{{ notice }}</p>
      <div class="auth-layout"><section class="admin-panel"><header><div><h2>策略版本台账</h2><p>已发布版本通过对象、动作、组织、患者关系、用途和资源状态联合计算。</p></div></header><div v-if="!policies.length" class="admin-empty">暂无授权策略，可在下方新增。</div><div v-else class="admin-table-wrap"><table class="admin-table auth-table"><thead><tr><th>策略</th><th>主体</th><th>资源 / 动作</th><th>条件</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="policy in policies" :key="policy.policy_id"><td><strong>{{ policy.policy_code }} v{{ policy.version_no }}</strong><small>优先级 {{ policy.priority }} · {{ policy.effect }}</small></td><td>{{ policy.subject_role_code || '任何有效角色' }}</td><td><code>{{ policy.resource_type }} / {{ policy.action_code }}</code><small>{{ policy.purpose_codes.join(' · ') || '任意用途' }}</small></td><td>{{ policy.patient_relationship_required ? `需 ${policy.relationship_types.join('/')}` : '不要求患者关系' }}</td><td><span class="admin-status" :class="policy.status === 'PUBLISHED' ? 'active' : ''">{{ policy.status }}</span><small>{{ formatDate(policy.published_at) }}</small></td><td><button class="task-action" :disabled="policy.status !== 'DRAFT' || policy.created_by === clinicalContext.userId || Boolean(busy)" @click="publish(policy)">{{ policy.created_by === clinicalContext.userId ? '不可自批' : '独立审批' }}</button></td></tr></tbody></table></div></section>
        <div class="auth-side"><section class="admin-panel admin-form-panel auth-form-panel"><header><div><h2>创建策略草案</h2><p>发布前必须独立审批。</p></div></header><form class="admin-form" @submit.prevent="createPolicy"><label><span>策略编码</span><input v-model="form.code" required placeholder="例：CLINICAL-DOCUMENT-READ" /></label><label><span>效果</span><select v-model="form.effect"><option value="ALLOW">允许</option><option value="DENY">显式拒绝</option></select></label><label><span>角色编码</span><input v-model="form.role" /></label><label><span>资源 / 动作</span><div class="split-fields"><input v-model="form.resource" /><input v-model="form.action" /></div></label><label><span>用途</span><input v-model="form.purpose" /></label><label class="auth-checkbox"><input v-model="form.relationshipRequired" type="checkbox" />要求当前照护关系</label><button class="button primary full" :disabled="Boolean(busy)">生成待审草案</button></form></section>
          <section class="admin-panel auth-simulation"><header><div><h2>访问模拟</h2><p>不读取病历正文，只返回命中链与决策。</p></div></header><div class="admin-form"><label><span>目标用户</span><input v-model="simulation.userId" /></label><label><span>目标角色任期</span><input v-model="simulation.roleId" /></label><button class="button secondary full" :disabled="Boolean(busy)" @click="simulate">使用运行时决策器模拟</button><div v-if="decision" class="decision-card" :class="decision.allowed ? 'allowed' : 'denied'"><strong>{{ decision.allowed ? '允许' : '拒绝' }} · {{ decision.reason_code }}</strong><p>{{ decision.explanation }}</p><small>命中策略 {{ decision.matched_policy_ids.length }} 条</small></div></div></section></div></div>
      <section class="admin-panel emergency-review"><header><div><h2>紧急访问事后复核</h2><p>请求人不能复核自己的紧急访问。</p></div></header><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>请求人 / 患者</th><th>最小范围</th><th>理由</th><th>时限</th><th>状态 / 复核</th></tr></thead><tbody><tr v-for="grant in grants" :key="grant.emergency_access_grant_id"><td><code>用户 …{{ grant.user_id.slice(-8) }}</code><small>患者 …{{ grant.patient_id.slice(-8) }}</small></td><td>{{ grant.resource_types.join('/') }}<small>{{ grant.action_codes.join('/') }}</small></td><td>{{ grant.reason }}</td><td>{{ formatDate(grant.expires_at) }}</td><td><span class="admin-status" :class="grant.status === 'ACTIVE' ? 'active' : ''">{{ grant.status }}</span><div v-if="grant.status !== 'REVIEWED'" class="review-actions"><button :disabled="grant.user_id === clinicalContext.userId || Boolean(busy)" @click="review(grant, 'APPROPRIATE')">合理</button><button :disabled="grant.user_id === clinicalContext.userId || Boolean(busy)" @click="review(grant, 'ESCALATED')">升级</button></div><small v-else>{{ grant.review_outcome }}</small></td></tr></tbody></table></div></section>
    </template>
  </section>
</template>
