<script setup lang="ts">
import { useQuery } from '@tanstack/vue-query';
import { computed, reactive, ref } from 'vue';
import type { ClinicalDiagnosisWire } from '../../generated/contracts';
import { confirmClinicalDiagnosis, correctClinicalDiagnosis, createClinicalDiagnosis, issueDiagnosisLease, listClinicalDiagnoses, stopClinicalDiagnosis } from '../../clinical-api';
import { developmentCopy } from '../../development-copy';
import BusinessActionDialog from '../components/BusinessActionDialog.vue';
import ClinicalPageState from '../components/ClinicalPageState.vue';
import { toClinicalIssue } from '../clinical-error';

type DiagnosisInput = { terminologyRelease: string; code: string; diagnosisText: string; diagnosisRole: 'PRIMARY' | 'SECONDARY' | 'DIFFERENTIAL'; certainty: 'PROVISIONAL' | 'CONFIRMED'; evidenceSummary: string; planSummary: string };
const input = reactive<DiagnosisInput>({ terminologyRelease: '2026B', code: 'I10.0', diagnosisText: '原发性高血压 2 级（高危）', diagnosisRole: 'PRIMARY', certainty: 'PROVISIONAL', evidenceSummary: '诊室血压与家庭监测记录', planSummary: '完善危险分层并复评' });
const edit = reactive<DiagnosisInput>({ ...input });
const formOpen = ref(false); const busy = ref<string | null>(null); const notice = ref('');
const controlId = ref<string | null>(null); const controlMode = ref<'correct' | 'stop' | null>(null); const reason = ref('');
const diagnosisFilter = ref<'ALL' | ClinicalDiagnosisWire['status']>('ALL'); const diagnosisSearch = ref('');
const diagnosesQuery = useQuery({ queryKey: ['clinical', 'diagnoses'], queryFn: async () => { const lease = await issueDiagnosisLease(); return { lease, diagnoses: await listClinicalDiagnoses(lease) }; }, retry: false, staleTime: 0, gcTime: 0 });
const issue = computed(() => diagnosesQuery.error.value ? toClinicalIssue(diagnosesQuery.error.value) : null);
const diagnoses = computed(() => diagnosesQuery.data.value?.diagnoses ?? []);
const filteredDiagnoses = computed(() => { const keyword = diagnosisSearch.value.trim().toLowerCase(); return diagnoses.value.filter((item) => (diagnosisFilter.value === 'ALL' || item.status === diagnosisFilter.value) && (!keyword || `${item.diagnosis_text} ${item.code} ${item.evidence_summary ?? ''}`.toLowerCase().includes(keyword))); });
const controlDiagnosis = computed(() => diagnoses.value.find((item) => item.diagnosis_id === controlId.value));
async function run(key: string, action: () => Promise<void>) { if (busy.value || !diagnosesQuery.data.value) return; busy.value = key; notice.value = ''; try { await action(); await diagnosesQuery.refetch(); } catch (error) { const next = toClinicalIssue(error); notice.value = `${next.code}：${next.message}`; } finally { busy.value = null; } }
function create() { const data = diagnosesQuery.data.value; if (!data) return; void run('create', async () => { await createClinicalDiagnosis(data.lease, input); formOpen.value = false; notice.value = '诊断已记录并固化当时术语版本'; }); }
function confirm(diagnosis: ClinicalDiagnosisWire) { const data = diagnosesQuery.data.value; if (!data) return; void run(`confirm:${diagnosis.diagnosis_id}`, async () => { await confirmClinicalDiagnosis(data.lease, diagnosis); notice.value = '诊断已由医生确认'; }); }
function beginControl(diagnosis: ClinicalDiagnosisWire, mode: 'correct' | 'stop') { controlId.value = diagnosis.diagnosis_id; controlMode.value = mode; reason.value = ''; Object.assign(edit, { terminologyRelease: diagnosis.terminology_release, code: diagnosis.code, diagnosisText: diagnosis.diagnosis_text, diagnosisRole: diagnosis.diagnosis_role, certainty: diagnosis.status === 'CONFIRMED' ? 'CONFIRMED' : 'PROVISIONAL', evidenceSummary: diagnosis.evidence_summary || '', planSummary: diagnosis.plan_summary || '' }); }
function submitControl() { const diagnosis = controlDiagnosis.value; const data = diagnosesQuery.data.value; if (!diagnosis || !data || !controlMode.value || !reason.value.trim()) return; const mode = controlMode.value; void run(`${mode}:${diagnosis.diagnosis_id}`, async () => { if (mode === 'correct') await correctClinicalDiagnosis(data.lease, diagnosis, { ...edit, correctionReason: reason.value.trim() }); else await stopClinicalDiagnosis(data.lease, diagnosis, reason.value.trim()); controlId.value = null; controlMode.value = null; notice.value = mode === 'correct' ? '已追加诊断更正版本，历史版本未覆盖' : '诊断已停止，历史事实保留'; }); }
function roleLabel(role: ClinicalDiagnosisWire['diagnosis_role']) { return role === 'PRIMARY' ? '主诊断' : role === 'SECONDARY' ? '其他诊断' : '鉴别诊断'; }
function statusLabel(status: ClinicalDiagnosisWire['status']) { return status === 'PROVISIONAL' ? '待确认' : status === 'CONFIRMED' ? '已确认' : '已停止'; }
</script>

<template>
  <section data-page-root class="content vue-native-page"><div class="page-heading"><div><p class="eyebrow">门诊 / 诊断与问题清单</p><h1>门诊诊断与问题清单</h1></div><div class="toolbar-actions"><RouterLink class="button secondary" to="/opd-record">返回门诊病历</RouterLink><button class="button primary" @click="formOpen = true">新增诊断</button></div></div>
    <section class="patient-strip"><div class="patient-avatar">{{ developmentCopy.patientAvatar }}</div><div><strong>{{ developmentCopy.outpatientPatientName }}</strong><span>当前门诊就诊</span></div><dl><div><dt>主诊断</dt><dd>活动唯一</dd></div><div><dt>术语语义</dt><dd>按版本快照</dd></div><div><dt>历史版本</dt><dd>不可覆盖</dd></div></dl><span class="lease-badge">当前患者 / 当前就诊</span></section>
    <section v-if="diagnosesQuery.data.value" class="admin-metrics clinical-workspace-metrics" aria-label="诊断统计"><article><span>诊断总数</span><strong>{{ diagnoses.length }}</strong><small>含活动与历史诊断</small></article><article><span>已确认</span><strong>{{ diagnoses.filter((item) => item.status === 'CONFIRMED').length }}</strong><small>医生确认的临床事实</small></article><article><span>待确认</span><strong>{{ diagnoses.filter((item) => item.status === 'PROVISIONAL').length }}</strong><small>需要人工审核</small></article><article><span>鉴别诊断</span><strong>{{ diagnoses.filter((item) => item.diagnosis_role === 'DIFFERENTIAL' && item.status !== 'STOPPED').length }}</strong><small>活动问题清单</small></article></section>
    <div v-if="notice" class="inline-notice" :class="{ error: notice.includes('：') }" role="status">{{ notice }}</div>
    <BusinessActionDialog :open="formOpen" title="新增诊断" description="保存时固化编码、名称、术语发布版和有效时间。" eyebrow="门诊诊断" confirm-label="保存诊断版本" :busy="busy === 'create'" width="wide" @cancel="formOpen = false" @confirm="create"><div class="dialog-grid"><label>术语发布版<select v-model="input.terminologyRelease"><option value="2026B">ICD-10-CN 2026B</option></select></label><label>诊断编码<select v-model="input.code"><option value="I10.0">I10.0 原发性高血压</option><option value="I10.9">I10.9 高血压病</option></select></label><label>诊断角色<select v-model="input.diagnosisRole"><option value="PRIMARY">主诊断</option><option value="SECONDARY">其他诊断</option><option value="DIFFERENTIAL">鉴别诊断</option></select></label><label>确定性<select v-model="input.certainty"><option value="PROVISIONAL">初步</option><option value="CONFIRMED">已确认</option></select></label></div><label>诊断文本<input v-model="input.diagnosisText" required maxlength="1000" /></label><label>诊断依据<textarea v-model="input.evidenceSummary" rows="2" maxlength="2000" /></label><label>鉴别/处置计划<textarea v-model="input.planSummary" rows="2" maxlength="2000" /></label></BusinessActionDialog>
    <ClinicalPageState v-if="diagnosesQuery.isPending.value" kind="loading" message="正在加载诊断版本链" /><ClinicalPageState v-else-if="issue" kind="error" :code="issue.code" :message="issue.message" @retry="diagnosesQuery.refetch()" />
    <div v-else-if="diagnosesQuery.data.value" class="diagnosis-layout"><section class="diagnosis-list"><div class="clinical-filter-bar"><label><span>检索诊断</span><input v-model="diagnosisSearch" type="search" placeholder="诊断名称、编码或依据" /></label><label><span>状态</span><select v-model="diagnosisFilter"><option value="ALL">全部状态</option><option value="PROVISIONAL">待确认</option><option value="CONFIRMED">已确认</option><option value="STOPPED">已停止</option></select></label><b>{{ filteredDiagnoses.length }} 条</b></div><div v-if="filteredDiagnoses.length === 0" class="empty-state diagnosis-empty"><span>诊</span><p>{{ diagnoses.length ? '当前筛选下没有诊断' : '当前就诊尚无诊断' }}</p><small>{{ diagnoses.length ? '调整关键词或状态筛选后重试' : '诊断经医生确认后才成为临床事实' }}</small></div><article v-for="diagnosis in filteredDiagnoses" :key="diagnosis.diagnosis_id" class="diagnosis-card"><header><div><span class="diagnosis-role" :class="diagnosis.diagnosis_role.toLowerCase()">{{ roleLabel(diagnosis.diagnosis_role) }}</span><strong>{{ diagnosis.diagnosis_text }}</strong><small>{{ diagnosis.code }} · {{ diagnosis.code_display_snapshot }} · {{ diagnosis.terminology_release }}</small></div><span class="task-state" :class="diagnosis.status.toLowerCase()">{{ statusLabel(diagnosis.status) }}</span></header><div class="diagnosis-body"><dl><div><dt>诊断依据</dt><dd>{{ diagnosis.evidence_summary || '未填写' }}</dd></div><div><dt>鉴别/计划</dt><dd>{{ diagnosis.plan_summary || '未填写' }}</dd></div></dl><p>不可变版本 v{{ diagnosis.version_no }} · 行版本 {{ diagnosis.row_version }} · 水印 {{ diagnosis.data_watermark.slice(0, 12) }}…</p></div>
      <footer><span>生效时间 {{ new Date(diagnosis.effective_at).toLocaleString('zh-CN') }}</span><div v-if="diagnosis.status !== 'STOPPED'" class="toolbar-actions"><button v-if="diagnosis.status === 'PROVISIONAL'" class="button primary" :disabled="busy === `confirm:${diagnosis.diagnosis_id}`" @click="confirm(diagnosis)">确认诊断</button><button class="button secondary" @click="beginControl(diagnosis, 'correct')">更正</button><button class="button danger" @click="beginControl(diagnosis, 'stop')">停止</button></div></footer></article></section><aside class="side-card diagnosis-safety"><div class="side-card-title"><h2>编码与安全</h2><span>3</span></div><ul><li>主诊断由数据库确保就诊内活动唯一。</li><li>更正只追加新版本，不修改历史术语快照。</li><li>AI 只能给出带来源候选，不能自动确认诊断。</li></ul></aside></div>
    <BusinessActionDialog :open="Boolean(controlDiagnosis && controlMode)" :title="controlMode === 'correct' ? '更正诊断' : '停止诊断'" :description="controlMode === 'correct' ? '更正只追加新版本，不会覆盖原始诊断事实。' : '停止代替物理删除，历史版本与审计证据继续保留。'" eyebrow="门诊诊断" :confirm-label="controlMode === 'correct' ? '追加更正版本' : '确认停止'" :danger="controlMode === 'stop'" :busy="Boolean(busy)" width="wide" @cancel="controlId = null; controlMode = null" @confirm="submitControl"><p class="dialog-warning">{{ controlDiagnosis?.diagnosis_text }} · {{ controlDiagnosis?.code }}</p><template v-if="controlMode === 'correct'"><div class="dialog-grid"><label>更正后诊断文本<input v-model="edit.diagnosisText" required /></label><label>诊断角色<select v-model="edit.diagnosisRole"><option value="PRIMARY">主诊断</option><option value="SECONDARY">其他诊断</option><option value="DIFFERENTIAL">鉴别诊断</option></select></label><label>确定性<select v-model="edit.certainty"><option value="PROVISIONAL">初步</option><option value="CONFIRMED">已确认</option></select></label></div></template><label>{{ controlMode === 'correct' ? '更正原因' : '停止原因' }}<textarea v-model="reason" required minlength="2" maxlength="1000" rows="3" placeholder="必填，将写入不可变控制事件" /></label></BusinessActionDialog>
  </section>
</template>
