<script setup lang="ts">
import { useQuery } from '@tanstack/vue-query';
import { computed, reactive, ref } from 'vue';
import type { ClinicalDiagnosisWire } from '../../generated/contracts';
import { confirmClinicalDiagnosis, correctClinicalDiagnosis, createClinicalDiagnosis, issueDiagnosisLease, listClinicalDiagnoses, stopClinicalDiagnosis } from '../../clinical-api';
import { developmentCopy } from '../../development-copy';
import ClinicalPageState from '../components/ClinicalPageState.vue';
import { toClinicalIssue } from '../clinical-error';

type DiagnosisInput = { terminologyRelease: string; code: string; diagnosisText: string; diagnosisRole: 'PRIMARY' | 'SECONDARY' | 'DIFFERENTIAL'; certainty: 'PROVISIONAL' | 'CONFIRMED'; evidenceSummary: string; planSummary: string };
const input = reactive<DiagnosisInput>({ terminologyRelease: '2026B', code: 'I10.0', diagnosisText: '原发性高血压 2 级（高危）', diagnosisRole: 'PRIMARY', certainty: 'PROVISIONAL', evidenceSummary: '诊室血压与家庭监测记录', planSummary: '完善危险分层并复评' });
const edit = reactive<DiagnosisInput>({ ...input });
const formOpen = ref(false); const busy = ref<string | null>(null); const notice = ref('');
const controlId = ref<string | null>(null); const controlMode = ref<'correct' | 'stop' | null>(null); const reason = ref('');
const diagnosesQuery = useQuery({ queryKey: ['clinical', 'diagnoses'], queryFn: async () => { const lease = await issueDiagnosisLease(); return { lease, diagnoses: await listClinicalDiagnoses(lease) }; }, retry: false, staleTime: 0, gcTime: 0 });
const issue = computed(() => diagnosesQuery.error.value ? toClinicalIssue(diagnosesQuery.error.value) : null);
async function run(key: string, action: () => Promise<void>) { if (busy.value || !diagnosesQuery.data.value) return; busy.value = key; notice.value = ''; try { await action(); await diagnosesQuery.refetch(); } catch (error) { const next = toClinicalIssue(error); notice.value = `${next.code}：${next.message}`; } finally { busy.value = null; } }
function create() { const data = diagnosesQuery.data.value; if (!data) return; void run('create', async () => { await createClinicalDiagnosis(data.lease, input); formOpen.value = false; notice.value = '诊断已记录并固化当时术语版本'; }); }
function confirm(diagnosis: ClinicalDiagnosisWire) { const data = diagnosesQuery.data.value; if (!data) return; void run(`confirm:${diagnosis.diagnosis_id}`, async () => { await confirmClinicalDiagnosis(data.lease, diagnosis); notice.value = '诊断已由医生确认'; }); }
function beginControl(diagnosis: ClinicalDiagnosisWire, mode: 'correct' | 'stop') { controlId.value = diagnosis.diagnosis_id; controlMode.value = mode; reason.value = ''; Object.assign(edit, { terminologyRelease: diagnosis.terminology_release, code: diagnosis.code, diagnosisText: diagnosis.diagnosis_text, diagnosisRole: diagnosis.diagnosis_role, certainty: diagnosis.status === 'CONFIRMED' ? 'CONFIRMED' : 'PROVISIONAL', evidenceSummary: diagnosis.evidence_summary || '', planSummary: diagnosis.plan_summary || '' }); }
function submitControl(diagnosis: ClinicalDiagnosisWire) { const data = diagnosesQuery.data.value; if (!data || !controlMode.value || !reason.value.trim()) return; const mode = controlMode.value; void run(`${mode}:${diagnosis.diagnosis_id}`, async () => { if (mode === 'correct') await correctClinicalDiagnosis(data.lease, diagnosis, { ...edit, correctionReason: reason.value.trim() }); else await stopClinicalDiagnosis(data.lease, diagnosis, reason.value.trim()); controlId.value = null; controlMode.value = null; notice.value = mode === 'correct' ? '已追加诊断更正版本，历史版本未覆盖' : '诊断已停止，历史事实保留'; }); }
function roleLabel(role: ClinicalDiagnosisWire['diagnosis_role']) { return role === 'PRIMARY' ? '主诊断' : role === 'SECONDARY' ? '其他诊断' : '鉴别诊断'; }
function statusLabel(status: ClinicalDiagnosisWire['status']) { return status === 'PROVISIONAL' ? '待确认' : status === 'CONFIRMED' ? '已确认' : '已停止'; }
</script>

<template>
  <section data-page-root class="content vue-native-page"><div class="page-heading"><div><p class="eyebrow">门诊 / 诊断与问题清单</p><h1>门诊诊断与问题清单</h1></div><div class="toolbar-actions"><RouterLink class="button secondary" to="/opd-record">返回门诊病历</RouterLink><button class="button primary" @click="formOpen = !formOpen">新增诊断</button></div></div>
    <section class="patient-strip"><div class="patient-avatar">{{ developmentCopy.patientAvatar }}</div><div><strong>{{ developmentCopy.outpatientPatientName }}</strong><span>当前门诊就诊</span></div><dl><div><dt>主诊断</dt><dd>活动唯一</dd></div><div><dt>术语语义</dt><dd>按版本快照</dd></div><div><dt>历史版本</dt><dd>不可覆盖</dd></div></dl><span class="lease-badge">当前患者 / 当前就诊</span></section>
    <div v-if="notice" class="inline-notice" :class="{ error: notice.includes('：') }" role="status">{{ notice }}</div>
    <section v-if="formOpen" class="diagnosis-form" aria-label="新增诊断"><div><h2>记录诊断</h2><p>保存时固化编码、名称、术语发布版和有效时间。</p></div><label>术语发布版<select v-model="input.terminologyRelease"><option value="2026B">ICD-10-CN 2026B</option></select></label><label>诊断编码<select v-model="input.code"><option value="I10.0">I10.0 原发性高血压</option><option value="I10.9">I10.9 高血压病</option></select></label><label>诊断角色<select v-model="input.diagnosisRole"><option value="PRIMARY">主诊断</option><option value="SECONDARY">其他诊断</option><option value="DIFFERENTIAL">鉴别诊断</option></select></label><label>确定性<select v-model="input.certainty"><option value="PROVISIONAL">初步</option><option value="CONFIRMED">已确认</option></select></label><label class="wide">诊断文本<input v-model="input.diagnosisText" maxlength="1000" /></label><label class="wide">诊断依据<textarea v-model="input.evidenceSummary" rows="2" maxlength="2000" /></label><label class="wide">鉴别/处置计划<textarea v-model="input.planSummary" rows="2" maxlength="2000" /></label><div class="toolbar-actions"><button class="button secondary" @click="formOpen = false">取消</button><button class="button primary" :disabled="busy === 'create' || !input.diagnosisText.trim()" @click="create">{{ busy === 'create' ? '正在保存…' : '保存诊断版本' }}</button></div></section>
    <ClinicalPageState v-if="diagnosesQuery.isPending.value" kind="loading" message="正在加载诊断版本链" /><ClinicalPageState v-else-if="issue" kind="error" :code="issue.code" :message="issue.message" @retry="diagnosesQuery.refetch()" />
    <div v-else-if="diagnosesQuery.data.value" class="diagnosis-layout"><section class="diagnosis-list"><div v-if="diagnosesQuery.data.value.diagnoses.length === 0" class="empty-state diagnosis-empty"><span>诊</span><p>当前就诊尚无诊断</p><small>诊断经医生确认后才成为临床事实</small></div><article v-for="diagnosis in diagnosesQuery.data.value.diagnoses" :key="diagnosis.diagnosis_id" class="diagnosis-card"><header><div><span class="diagnosis-role" :class="diagnosis.diagnosis_role.toLowerCase()">{{ roleLabel(diagnosis.diagnosis_role) }}</span><strong>{{ diagnosis.diagnosis_text }}</strong><small>{{ diagnosis.code }} · {{ diagnosis.code_display_snapshot }} · {{ diagnosis.terminology_release }}</small></div><span class="task-state" :class="diagnosis.status.toLowerCase()">{{ statusLabel(diagnosis.status) }}</span></header><div class="diagnosis-body"><dl><div><dt>诊断依据</dt><dd>{{ diagnosis.evidence_summary || '未填写' }}</dd></div><div><dt>鉴别/计划</dt><dd>{{ diagnosis.plan_summary || '未填写' }}</dd></div></dl><p>不可变版本 v{{ diagnosis.version_no }} · 行版本 {{ diagnosis.row_version }} · 水印 {{ diagnosis.data_watermark.slice(0, 12) }}…</p></div>
      <div v-if="controlId === diagnosis.diagnosis_id && controlMode === 'correct'" class="diagnosis-control"><label>更正后诊断文本<input v-model="edit.diagnosisText" /></label><label>诊断角色<select v-model="edit.diagnosisRole"><option value="PRIMARY">主诊断</option><option value="SECONDARY">其他诊断</option><option value="DIFFERENTIAL">鉴别诊断</option></select></label><label>确定性<select v-model="edit.certainty"><option value="PROVISIONAL">初步</option><option value="CONFIRMED">已确认</option></select></label><label class="wide">更正原因<textarea v-model="reason" rows="2" maxlength="1000" /></label><div class="toolbar-actions"><button class="button secondary" @click="controlId = null">返回</button><button class="button primary" :disabled="!reason.trim() || busy === `correct:${diagnosis.diagnosis_id}`" @click="submitControl(diagnosis)">追加更正版本</button></div></div>
      <div v-if="controlId === diagnosis.diagnosis_id && controlMode === 'stop'" class="diagnosis-control stop"><label class="wide">停止原因<textarea v-model="reason" rows="2" maxlength="1000" placeholder="必填，原诊断版本仍保留" /></label><div class="toolbar-actions"><button class="button secondary" @click="controlId = null">返回</button><button class="button danger" :disabled="!reason.trim() || busy === `stop:${diagnosis.diagnosis_id}`" @click="submitControl(diagnosis)">确认停止</button></div></div>
      <footer><span>生效时间 {{ new Date(diagnosis.effective_at).toLocaleString('zh-CN') }}</span><div v-if="diagnosis.status !== 'STOPPED' && controlId !== diagnosis.diagnosis_id" class="toolbar-actions"><button v-if="diagnosis.status === 'PROVISIONAL'" class="button primary" :disabled="busy === `confirm:${diagnosis.diagnosis_id}`" @click="confirm(diagnosis)">确认诊断</button><button class="button secondary" @click="beginControl(diagnosis, 'correct')">更正</button><button class="button danger" @click="beginControl(diagnosis, 'stop')">停止</button></div></footer></article></section><aside class="side-card diagnosis-safety"><div class="side-card-title"><h2>编码与安全</h2><span>3</span></div><ul><li>主诊断由数据库确保就诊内活动唯一。</li><li>更正只追加新版本，不修改历史术语快照。</li><li>AI 只能给出带来源候选，不能自动确认诊断。</li></ul></aside></div>
  </section>
</template>
