<script setup lang="ts">
import { useQuery } from '@tanstack/vue-query';
import { computed, reactive, ref } from 'vue';
import { clinicalContext } from '../../clinical-api';
import type { EmergencyCoordinationCaseWire, EncounterDomainSwitchWire } from '../../generated/contracts';
import {
  correctEncounterDomainSwitch, createEmergencyCoordinationCase, issueEmergencyEncounterLease,
  issueEmergencyLease, listEmergencyCoordinationCases, listEncounterDomainSwitches,
  recordEncounterDomainSwitch, transitionEmergencyCoordinationCase, updateEmergencyCoordinationCase,
  voidEmergencyCoordinationCase, voidEncounterDomainSwitch,
} from '../../api/emergency';
import AdminActionDialog from '../components/AdminActionDialog.vue';
import AdminConfirmDialog from '../components/AdminConfirmDialog.vue';
import ClinicalPageState from '../components/ClinicalPageState.vue';
import EmergencyPatientStrip from '../components/EmergencyPatientStrip.vue';
import { toClinicalIssue } from '../clinical-error';

const patientLease = useQuery({ queryKey: ['emergency', 'handoff', 'patient-lease'], queryFn: () => issueEmergencyLease('EMERGENCY_HANDOFF'), retry: false, staleTime: 5 * 60_000, gcTime: 0 });
const commandLease = useQuery({ queryKey: ['emergency', 'handoff', 'command-lease'], queryFn: () => issueEmergencyEncounterLease('EMERGENCY_HANDOFF_COMMAND'), retry: false, staleTime: 5 * 60_000, gcTime: 0 });
const casesQuery = useQuery({ queryKey: ['emergency', 'handoff', 'coordination'], queryFn: () => listEmergencyCoordinationCases(patientLease.data.value!), enabled: () => Boolean(patientLease.data.value), retry: false });
const switchesQuery = useQuery({ queryKey: ['emergency', 'handoff', 'switches'], queryFn: () => listEncounterDomainSwitches(patientLease.data.value!), enabled: () => Boolean(patientLease.data.value), retry: false });
const issue = computed(() => { const failed = [patientLease, commandLease, casesQuery, switchesQuery].find((query) => query.error.value); return failed ? toClinicalIssue(failed.error.value) : null; });
const pending = computed(() => [patientLease, commandLease, casesQuery, switchesQuery].some((query) => query.isPending.value));
const cases = computed(() => casesQuery.data.value ?? []); const switches = computed(() => switchesQuery.data.value ?? []);
const openCases = computed(() => cases.value.filter((item) => item.status === 'OPEN' || item.status === 'ACKNOWLEDGED'));
const overdue = computed(() => openCases.value.filter((item) => new Date(item.due_at).getTime() < Date.now()));

const caseForm = reactive({ case_type: 'CONSULTATION' as 'CONSULTATION'|'HANDOFF'|'TRANSFER', priority: 'URGENT' as 'IMMEDIATE'|'URGENT'|'ROUTINE', target_unit: '', requested_to: clinicalContext.collaboratorUserId as string|null, summary: '', risk_summary: '', due_at: new Date(Date.now()+30*60_000).toISOString().slice(0,16) });
const switchForm = reactive({ to_encounter_id: '', to_domain: 'INPATIENT' as 'OUTPATIENT'|'EMERGENCY'|'INPATIENT', reason: '', correction_reason: '' });
const editorOpen=ref(false); const switchOpen=ref(false); const editing=ref<EmergencyCoordinationCaseWire|null>(null); const editingSwitch=ref<EncounterDomainSwitchWire|null>(null);
const voidTarget=ref<EmergencyCoordinationCaseWire|null>(null); const voidReason=ref(''); const voidSwitchTarget=ref<EncounterDomainSwitchWire|null>(null); const switchVoidReason=ref(''); const busy=ref(''); const notice=ref('');

const typeLabel:Record<string,string>={CONSULTATION:'急会诊',HANDOFF:'跨班交接',TRANSFER:'跨区域转运'}; const priorityLabel:Record<string,string>={IMMEDIATE:'立即',URGENT:'紧急',ROUTINE:'常规'}; const statusLabel:Record<string,string>={OPEN:'待接收',ACKNOWLEDGED:'已接收',COMPLETED:'已完成',VOIDED:'已作废'};
function formatDate(value:string|null|undefined){return value?new Intl.DateTimeFormat('zh-CN',{dateStyle:'medium',timeStyle:'short',hour12:false}).format(new Date(value)):'—';}
function resetCase(){editing.value=null;Object.assign(caseForm,{case_type:'CONSULTATION',priority:'URGENT',target_unit:'',requested_to:clinicalContext.collaboratorUserId,summary:'',risk_summary:'',due_at:new Date(Date.now()+30*60_000).toISOString().slice(0,16)});}
function openCreate(type:'CONSULTATION'|'HANDOFF'|'TRANSFER'='CONSULTATION'){resetCase();caseForm.case_type=type;editorOpen.value=true;}
function openEdit(item:EmergencyCoordinationCaseWire){editing.value=item;Object.assign(caseForm,{case_type:item.case_type,priority:item.priority,target_unit:item.target_unit,requested_to:item.requested_to,summary:item.summary,risk_summary:item.risk_summary,due_at:new Date(item.due_at).toISOString().slice(0,16)});editorOpen.value=true;}
async function reload(){notice.value='';await Promise.all([casesQuery.refetch(),switchesQuery.refetch()]);}
async function saveCase(){const lease=commandLease.data.value;if(!lease||busy.value||!caseForm.target_unit.trim()||!caseForm.summary.trim()||!caseForm.risk_summary.trim())return;busy.value='case';try{const input={priority:caseForm.priority,target_unit:caseForm.target_unit.trim(),requested_to:caseForm.requested_to||null,summary:caseForm.summary.trim(),risk_summary:caseForm.risk_summary.trim(),due_at:new Date(caseForm.due_at).toISOString()};if(editing.value)await updateEmergencyCoordinationCase(lease,editing.value,input);else await createEmergencyCoordinationCase(lease,{case_type:caseForm.case_type,...input});notice.value=editing.value?'协同单已更新，时限和风险会立即影响待办。':'协同单已创建并进入接收人待办。';editorOpen.value=false;resetCase();await casesQuery.refetch();}catch(error){const next=toClinicalIssue(error);notice.value=`${next.code}：${next.message}`;}finally{busy.value='';}}
async function transition(item:EmergencyCoordinationCaseWire,action:'ACKNOWLEDGE'|'COMPLETE'){const lease=commandLease.data.value;if(!lease||busy.value)return;busy.value=item.coordination_case_id;try{await transitionEmergencyCoordinationCase(lease,item,action);notice.value=action==='ACKNOWLEDGE'?'接收责任已留痕。':'协同闭环已留痕。';await casesQuery.refetch();}catch(error){const next=toClinicalIssue(error);notice.value=`${next.code}：${next.message}`;}finally{busy.value='';}}
async function confirmVoid(){const lease=commandLease.data.value;const target=voidTarget.value;if(!lease||!target||voidReason.value.trim().length<4)return;busy.value='void';try{await voidEmergencyCoordinationCase(lease,target,voidReason.value.trim());notice.value='协同单已逻辑作废，不再计入未完任务。';voidTarget.value=null;voidReason.value='';await casesQuery.refetch();}catch(error){const next=toClinicalIssue(error);notice.value=`${next.code}：${next.message}`;}finally{busy.value='';}}
function openCreateSwitch(){editingSwitch.value=null;Object.assign(switchForm,{to_encounter_id:'',to_domain:'INPATIENT',reason:'',correction_reason:''});switchOpen.value=true;}
function openEditSwitch(item:EncounterDomainSwitchWire){editingSwitch.value=item;Object.assign(switchForm,{to_encounter_id:item.to_encounter_id,to_domain:item.to_domain,reason:item.reason,correction_reason:''});switchOpen.value=true;}
async function saveSwitch(){const lease=patientLease.data.value;if(!lease||busy.value||!switchForm.to_encounter_id.trim()||!switchForm.reason.trim()||(editingSwitch.value&&switchForm.correction_reason.trim().length<4))return;busy.value='switch';try{const input={from_encounter_id:clinicalContext.emergencyEncounterId,to_encounter_id:switchForm.to_encounter_id.trim(),from_domain:'EMERGENCY' as const,to_domain:switchForm.to_domain,reason:switchForm.reason.trim(),switched_at:new Date().toISOString()};if(editingSwitch.value)await correctEncounterDomainSwitch(lease,editingSwitch.value,{...input,correction_reason:switchForm.correction_reason.trim()});else await recordEncounterDomainSwitch(lease,input);notice.value='域切换已校验同一患者与就诊类型后留存。';switchOpen.value=false;await switchesQuery.refetch();}catch(error){const next=toClinicalIssue(error);notice.value=`${next.code}：${next.message}`;}finally{busy.value='';}}
async function confirmVoidSwitch(){const lease=patientLease.data.value;const target=voidSwitchTarget.value;if(!lease||!target||switchVoidReason.value.trim().length<4)return;busy.value='switch-void';try{await voidEncounterDomainSwitch(lease,target,switchVoidReason.value.trim());voidSwitchTarget.value=null;switchVoidReason.value='';notice.value='域切换已逻辑作废。';await switchesQuery.refetch();}catch(error){const next=toClinicalIssue(error);notice.value=`${next.code}：${next.message}`;}finally{busy.value='';}}
</script>

<template><section data-page-root class="content admin-content vue-native-page emergency-crud-page">
  <div class="page-head"><div class="page-title"><h1>急诊会诊、交接与转运</h1><p>急诊患者专用协同单，不再复用住院病区交班数据</p></div><div class="head-actions"><button class="btn" @click="openCreate('CONSULTATION')">发起急会诊</button><button class="btn" @click="openCreate('HANDOFF')">新建交接</button><button class="btn" @click="openCreate('TRANSFER')">新建转运</button><button class="btn primary" @click="openCreateSwitch">记录域切换</button></div></div>
  <ClinicalPageState v-if="pending" kind="loading" message="正在读取急会诊、交接和转运协同单"/><ClinicalPageState v-else-if="issue" kind="error" :code="issue.code" :message="issue.message" @retry="reload"/>
  <template v-else><EmergencyPatientStrip/><p v-if="notice" class="admin-notice" role="status">{{notice}}</p>
    <div class="metric-grid emergency-metrics"><div class="metric"><div class="name">未完协同</div><div class="value">{{openCases.length}}</div><div class="trend">会诊、交接、转运</div></div><div class="metric"><div class="name">已超时</div><div class="value danger-text">{{overdue.length}}</div><div class="trend">按 due_at 真实计算</div></div><div class="metric"><div class="name">已完成</div><div class="value">{{cases.filter(i=>i.status==='COMPLETED').length}}</div><div class="trend">接收与完成双时间</div></div><div class="metric"><div class="name">域切换</div><div class="value">{{switches.length}}</div><div class="trend">支持门诊/急诊/住院</div></div></div>
    <div class="grid secondary-grid emergency-prototype-layout"><section class="card scroll-card emergency-prototype-main"><div class="card-head">当前急诊协同单</div><div v-if="!cases.length" class="clinical-empty-state rich"><strong>暂无协同单</strong><p>发起后将进入指定接收人待办。</p></div><div v-else class="admin-table-wrap"><table class="table emergency-compact-table"><thead><tr><th>类型/时限</th><th>目标单元</th><th>摘要/风险</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="item in cases" :key="item.coordination_case_id" :class="{'is-voided':item.status==='VOIDED'}"><td><b>{{typeLabel[item.case_type]}}·{{priorityLabel[item.priority]}}</b><br><span :class="{'danger-text':new Date(item.due_at).getTime()<Date.now()&&['OPEN','ACKNOWLEDGED'].includes(item.status)}">{{formatDate(item.due_at)}}</span></td><td>{{item.target_unit}}</td><td><b>{{item.summary}}</b><br><span class="meta">{{item.risk_summary}}</span></td><td><span class="status" :class="item.status==='OPEN'?'amber':item.status==='ACKNOWLEDGED'?'blue':item.status==='COMPLETED'?'green':'gray'">{{statusLabel[item.status]}}</span></td><td><span class="inline-actions"><button class="btn sm" :disabled="item.status!=='OPEN'||Boolean(busy)" @click="openEdit(item)">编辑</button><button class="btn sm" :disabled="item.status!=='OPEN'||Boolean(busy)" @click="transition(item,'ACKNOWLEDGE')">接收</button><button class="btn sm primary" :disabled="item.status!=='ACKNOWLEDGED'||Boolean(busy)" @click="transition(item,'COMPLETE')">完成</button><button class="btn sm danger" :disabled="!['OPEN','ACKNOWLEDGED'].includes(item.status)||Boolean(busy)" @click="voidTarget=item">删除</button></span></td></tr></tbody></table></div></section>
    <aside class="card scroll-card emergency-prototype-side"><div class="card-head">域切换与接收门禁</div><div class="card-body"><div v-for="item in switches" :key="item.domain_switch_id" class="queue-item"><div class="queue-title">{{item.from_domain}}→{{item.to_domain}}<span class="status green">已留痕</span></div><div class="queue-meta">{{item.reason}}·{{formatDate(item.switched_at)}}</div><span class="inline-actions"><button class="btn sm" @click="openEditSwitch(item)">更正</button><button class="btn sm danger" @click="voidSwitchTarget=item">删除</button></span></div><div v-if="!switches.length" class="clinical-empty-state compact"><strong>暂无域切换</strong><span>转住院必须引用同一患者的真实住院就诊。</span></div><div class="notice hard"><div class="notice-title">接收人门禁</div>指定接收人后仅本人可接收；交接/转运不允许申请人自我接收。</div></div></aside></div>
  </template>
  <AdminActionDialog v-model:open="editorOpen" :title="editing?'编辑协同单':'新建急诊协同单'" description="保存后会改变接收人待办、超时统计与急诊闭环门禁。" eyebrow="急诊 / 协同" :busy="busy==='case'" size="large" @update:open="!$event&&resetCase()"><form class="admin-form" @submit.prevent="saveCase"><label><span>类型</span><select v-model="caseForm.case_type" :disabled="Boolean(editing)"><option value="CONSULTATION">急会诊</option><option value="HANDOFF">跨班交接</option><option value="TRANSFER">跨区转运</option></select></label><label><span>优先级</span><select v-model="caseForm.priority"><option value="IMMEDIATE">立即</option><option value="URGENT">紧急</option><option value="ROUTINE">常规</option></select></label><label><span>目标科室/单元</span><input v-model="caseForm.target_unit" required/></label><label><span>指定接收人 UUID（可留空）</span><input v-model="caseForm.requested_to"/></label><label><span>临床摘要</span><textarea v-model="caseForm.summary" rows="3" required/></label><label><span>风险、未回结果与未完任务</span><textarea v-model="caseForm.risk_summary" rows="3" required/></label><label><span>应答/完成时限</span><input v-model="caseForm.due_at" type="datetime-local" required/></label><button class="button primary" :disabled="Boolean(busy)">{{busy==='case'?'保存中…':'验证并保存'}}</button></form></AdminActionDialog>
  <AdminActionDialog v-model:open="switchOpen" :title="editingSwitch?'更正域切换':'记录域切换'" description="后端强制校验源/目标就诊属于同一患者，且就诊类型与选择域一致。" eyebrow="急诊 / 转归" :busy="busy==='switch'"><form class="admin-form" @submit.prevent="saveSwitch"><label><span>目标就诊 UUID</span><input v-model="switchForm.to_encounter_id" required/></label><label><span>目标域</span><select v-model="switchForm.to_domain"><option value="INPATIENT">住院</option><option value="OUTPATIENT">门诊</option></select></label><label><span>切换原因</span><textarea v-model="switchForm.reason" rows="3" required/></label><label v-if="editingSwitch"><span>更正原因</span><textarea v-model="switchForm.correction_reason" rows="2" required minlength="4"/></label><button class="button primary" :disabled="Boolean(busy)">验证并保存</button></form></AdminActionDialog>
  <AdminConfirmDialog :open="Boolean(voidTarget)" title="删除急诊协同单" description="执行逻辑作废，已完成协同不可删除。" confirm-label="确认删除" :busy="busy==='void'" @update:open="!$event&&(voidTarget=null)" @confirm="confirmVoid"><label class="admin-confirm-reason"><span>作废原因</span><textarea v-model="voidReason" rows="3" required minlength="4"/></label></AdminConfirmDialog>
  <AdminConfirmDialog :open="Boolean(voidSwitchTarget)" title="删除域切换" description="将逻辑作废错误的转归记录。" confirm-label="确认删除" :busy="busy==='switch-void'" @update:open="!$event&&(voidSwitchTarget=null)" @confirm="confirmVoidSwitch"><label class="admin-confirm-reason"><span>作废原因</span><textarea v-model="switchVoidReason" rows="3" required minlength="4"/></label></AdminConfirmDialog>
</section></template>
