<script setup lang="ts">
import { useQuery } from '@tanstack/vue-query';
import { computed, reactive, ref } from 'vue';
import { useRoute } from 'vue-router';
import type { ClinicalResultWire, CriticalValueWire } from '../../generated/contracts';
import { authSession } from '../../auth-session';
import { acknowledgeCriticalValue, clinicalContext, correctClinicalResult, createClinicalResult, disposeCriticalValue, issueOrderLease, issueResultLease, listClinicalOrders, listClinicalResults, type ResultObservationInput } from '../../clinical-api';
import { developmentCopy } from '../../development-copy';
import BusinessActionDialog from '../components/BusinessActionDialog.vue';
import ClinicalPageState from '../components/ClinicalPageState.vue';
import InpatientPrototypeRail from '../components/InpatientPrototypeRail.vue';
import { toClinicalIssue } from '../clinical-error';

type ResultForm = { executionTaskId: string; reportType: 'LAB' | 'IMAGING'; itemCode: string; itemName: string; numericValue: number; unit: string; referenceLow: number; referenceHigh: number; abnormalFlag: ResultObservationInput['abnormalFlag']; conclusion: string };
type Disposition = { assessment: string; actionTaken: string; outcome: string; retestRequired: boolean };
type Correction = { value: number; flag: ResultObservationInput['abnormalFlag']; conclusion: string; reason: string };
const route = useRoute();
const mode = computed<'outpatient' | 'inpatient'>(() => route.name === 'ip-results' ? 'inpatient' : 'outpatient');
const form = reactive<ResultForm>({ executionTaskId: '', reportType: 'LAB', itemCode: 'K', itemName: '血钾', numericValue: 4.2, unit: 'mmol/L', referenceLow: 3.5, referenceHigh: 5.5, abnormalFlag: 'NORMAL', conclusion: '本次检验结果已审核' });
const formOpen = ref(false); const busy = ref<string | null>(null); const notice = ref('');
const resultFilter = ref<'ALL' | 'LAB' | 'IMAGING' | 'ABNORMAL'>('ALL'); const resultSearch = ref('');
const dispositionById = reactive<Record<string, Disposition>>({}); const correctionById = reactive<Record<string, Correction>>({});
const dispositionCriticalId = ref<string | null>(null); const correctionResultId = ref<string | null>(null);
const resultsQuery = useQuery({ queryKey: computed(() => [
  'clinical', 'results', mode.value,
  mode.value === 'inpatient' ? clinicalContext.inpatientPatientId : clinicalContext.patientId,
  mode.value === 'inpatient' ? clinicalContext.inpatientEncounterId : clinicalContext.encounterId,
]), queryFn: async () => { const [lease, orderLease] = await Promise.all([issueResultLease(mode.value), issueOrderLease(mode.value)]); const [results, orders] = await Promise.all([listClinicalResults(lease, mode.value), listClinicalOrders(orderLease, mode.value)]); return { lease, results, orders }; }, retry: false, staleTime: 0, gcTime: 0 });
const issue = computed(() => resultsQuery.error.value ? toClinicalIssue(resultsQuery.error.value) : null);
const results = computed(() => resultsQuery.data.value?.results ?? []);
const criticalValues = computed(() => results.value.flatMap((result) => result.critical_values));
const abnormalResults = computed(() => results.value.filter((result) => result.observations.some((item) => item.abnormal_flag !== 'NORMAL')));
const filteredResults = computed(() => { const keyword = resultSearch.value.trim().toLowerCase(); return results.value.filter((result) => (resultFilter.value === 'ALL' || result.report_type === resultFilter.value || (resultFilter.value === 'ABNORMAL' && result.observations.some((item) => item.abnormal_flag !== 'NORMAL'))) && (!keyword || `${result.conclusion} ${result.observations.map((item) => `${item.item_name} ${item.item_code}`).join(' ')}`.toLowerCase().includes(keyword))); });
const eligibleTasks = computed(() => { const data = resultsQuery.data.value; if (!data) return []; const reported = new Set(data.results.map((result) => result.execution_task_id)); return data.orders.flatMap((order) => order.execution_tasks.filter((task) => task.task_state === 'COMPLETED' && !reported.has(task.execution_task_id)).map((task) => ({ task, item: order.items.find((item) => item.order_item_id === task.order_item_id) }))).filter((entry) => entry.item?.item_type === 'LAB' || entry.item?.item_type === 'IMAGING'); });
const dispositionCritical = computed(() => criticalValues.value.find((item) => item.critical_value_id === dispositionCriticalId.value));
const correctionResult = computed(() => results.value.find((item) => item.result_id === correctionResultId.value));
const activeRoleCodes = computed(() => new Set(authSession.user?.role_codes ?? []));
const canAuthorLab = computed(() => activeRoleCodes.value.has('LAB_TECHNICIAN'));
const canAuthorImaging = computed(() => activeRoleCodes.value.has('RADIOLOGIST'));
const canAuthorAnyResult = computed(() => canAuthorLab.value || canAuthorImaging.value);
const authorableTasks = computed(() => eligibleTasks.value.filter((entry) =>
  entry.item?.item_type === 'LAB' ? canAuthorLab.value : canAuthorImaging.value));
const resultFormReady = computed(() => Boolean(
  authorableTasks.value.some((entry) => entry.task.execution_task_id === form.executionTaskId)
  && form.itemCode.trim() && form.itemName.trim() && form.unit.trim() && form.conclusion.trim()
  && Number.isFinite(form.numericValue) && Number.isFinite(form.referenceLow)
  && Number.isFinite(form.referenceHigh) && form.referenceLow <= form.referenceHigh,
));
const clinicalRoleCodes = new Set(['CLINICIAN', 'CHIEF_PHYSICIAN', 'ATTENDING_PHYSICIAN', 'SURGEON', 'EMERGENCY_PHYSICIAN', 'PEDIATRICIAN', 'ICU_PHYSICIAN']);
const canReceiveCritical = computed(() => [...activeRoleCodes.value].some((role) => clinicalRoleCodes.has(role) || role === 'REGISTERED_NURSE' || role === 'NURSE_MANAGER'));
const canDisposeCritical = computed(() => [...activeRoleCodes.value].some((role) => clinicalRoleCodes.has(role)));
function canAuthorResult(result: ClinicalResultWire) { return result.report_type === 'LAB' ? canAuthorLab.value : canAuthorImaging.value; }
function beginCreateResult() {
  const eligible = authorableTasks.value[0];
  form.executionTaskId = eligible?.task.execution_task_id ?? '';
  if (eligible) selectExecution();
  formOpen.value = true;
}
async function run(key: string, action: () => Promise<void>, success = '') { if (busy.value || !resultsQuery.data.value) return; busy.value = key; notice.value = ''; try { await action(); await resultsQuery.refetch(); if (success) notice.value = success; } catch (error) { const next = toClinicalIssue(error); notice.value = `${next.code}：${next.message}`; } finally { busy.value = null; } }
function selectExecution() { const selected = eligibleTasks.value.find((entry) => entry.task.execution_task_id === form.executionTaskId); if (!selected) return; form.reportType = selected.item?.item_type === 'IMAGING' ? 'IMAGING' : 'LAB'; form.itemCode = selected.item?.catalog_code || form.itemCode; form.itemName = selected.item?.display_name || form.itemName; }
function create() { const data = resultsQuery.data.value; if (!data || !resultFormReady.value) return; void run('create', async () => { await createClinicalResult(data.lease, form.executionTaskId, form.reportType, form.conclusion, { itemCode: form.itemCode, itemName: form.itemName, valueType: 'NUMERIC', numericValue: form.numericValue, unit: form.unit, referenceLow: form.referenceLow, referenceHigh: form.referenceHigh, abnormalFlag: form.abnormalFlag }, mode.value); formOpen.value = false; }, '结果报告已记录为不可变 v1'); }
function acknowledge(critical: CriticalValueWire) { const data = resultsQuery.data.value; if (!data) return; void run(`ack:${critical.critical_value_id}`, async () => { await acknowledgeCriticalValue(data.lease, critical, mode.value); }, '危急值已复读并确认接收，仍需完成临床处置'); }
function disposition(critical: CriticalValueWire) { return dispositionById[critical.critical_value_id] ?? (dispositionById[critical.critical_value_id] = { assessment: '', actionTaken: '', outcome: '', retestRequired: true }); }
function beginDisposition(critical: CriticalValueWire) { disposition(critical); dispositionCriticalId.value = critical.critical_value_id; }
function dispose() { const critical = dispositionCritical.value; const data = resultsQuery.data.value; if (!critical || !data) return; const input = disposition(critical); if (!input.assessment.trim() || !input.actionTaken.trim() || !input.outcome.trim()) return; void run(`dispose:${critical.critical_value_id}`, async () => { await disposeCriticalValue(data.lease, critical, input, mode.value); dispositionCriticalId.value = null; }, '危急值评估、措施、结果与复测决策已分别留痕'); }
function beginCorrection(result: ClinicalResultWire) { const first = result.observations[0]; if (!first) return; correctionById[result.result_id] = { value: first.numeric_value ?? 0, flag: first.abnormal_flag, conclusion: result.conclusion, reason: '' }; correctionResultId.value = result.result_id; }
function correct() { const result = correctionResult.value; const data = resultsQuery.data.value; if (!result || !data) return; const correction = correctionById[result.result_id]; const first = result.observations[0]; if (!correction || !first || !correction.reason.trim()) return; const observation: ResultObservationInput = { itemCode: first.item_code, itemName: first.item_name, valueType: first.value_type, numericValue: first.value_type === 'NUMERIC' ? correction.value : undefined, textValue: first.value_type === 'TEXT' ? (first.text_value || correction.conclusion) : undefined, unit: first.value_type === 'NUMERIC' ? (first.unit || undefined) : undefined, referenceLow: first.value_type === 'NUMERIC' ? (first.reference_low ?? undefined) : undefined, referenceHigh: first.value_type === 'NUMERIC' ? (first.reference_high ?? undefined) : undefined, abnormalFlag: first.value_type === 'TEXT' && ['CRITICAL_HIGH','CRITICAL_LOW'].includes(correction.flag) ? 'NORMAL' : correction.flag }; void run(`correct:${result.result_id}`, async () => { await correctClinicalResult(data.lease, result, correction.reason.trim(), correction.conclusion, observation, mode.value); delete correctionById[result.result_id]; correctionResultId.value = null; }, '已追加更正报告版本，原报告保持可追溯'); }
</script>

<template>
  <section data-page-root class="content vue-native-page"><div class="page-heading"><div><p class="eyebrow">{{ mode === 'inpatient' ? '住院 / 检查检验与危急值' : '门诊 / 检查检验与结果' }}</p><h1>{{ mode === 'inpatient' ? '住院检查检验与危急值' : '门诊检查检验与结果' }}</h1></div><div class="toolbar-actions"><RouterLink class="button secondary" :to="mode === 'inpatient' ? '/ip-orders' : '/opd-orders'">查看原医嘱</RouterLink><button v-if="canAuthorAnyResult" class="button primary" @click="beginCreateResult">录入结果</button><span v-else class="lease-badge">医生只读报告 / 处置危急值</span></div></div>
    <section class="patient-strip"><div class="patient-avatar">{{ developmentCopy.patientAvatar }}</div><div><strong>{{ mode === 'inpatient' ? developmentCopy.inpatientPatientName : (clinicalContext.patientDisplayName || developmentCopy.outpatientPatientName) }}</strong><span>{{ mode === 'inpatient' ? '当前住院就诊' : '当前门诊就诊' }}</span></div><dl><div><dt>报告版本</dt><dd>不可覆盖</dd></div><div><dt>危急值</dt><dd>接收 ≠ 处置</dd></div><div><dt>来源关联</dt><dd>医嘱 / 执行</dd></div></dl><span class="lease-badge">当前患者 / 当前就诊</span></section><section v-if="resultsQuery.data.value" class="admin-metrics clinical-workspace-metrics" aria-label="结果统计"><article><span>已签发报告</span><strong>{{ results.length }}</strong><small>检验与检查结果</small></article><article><span>异常报告</span><strong>{{ abnormalResults.length }}</strong><small>至少一项非正常</small></article><article><span>开放危急值</span><strong>{{ criticalValues.filter((item) => item.state !== 'DISPOSED').length }}</strong><small>接收与处置分开</small></article><article><span>待录入结果</span><strong>{{ eligibleTasks.length }}</strong><small>已完成执行且未报告</small></article></section><div v-if="notice" class="inline-notice" :class="{ error: notice.includes('：') }" role="status">{{ notice }}</div>
    <BusinessActionDialog :open="formOpen && Boolean(resultsQuery.data.value)" title="录入已审核结果" :description="developmentCopy.resultEntryNotice" :eyebrow="mode === 'inpatient' ? '住院检查检验' : '门诊检查检验'" confirm-label="签发结果 v1" :busy="busy === 'create'" :confirm-disabled="!resultFormReady" width="wide" @cancel="formOpen = false" @confirm="create"><label>已完成执行<select v-model="form.executionTaskId" required @change="selectExecution"><option value="">请选择</option><option v-for="entry in authorableTasks" :key="entry.task.execution_task_id" :value="entry.task.execution_task_id">{{ entry.item?.display_name }} · …{{ entry.task.execution_task_id.slice(-8) }}</option></select></label><p v-if="authorableTasks.length === 0" class="dialog-warning">当前岗位没有可签发的已完成执行任务；检验与影像报告按岗位分离。</p><div class="dialog-grid"><label>项目编码<input v-model="form.itemCode" required /></label><label>项目名称<input v-model="form.itemName" required /></label><label>结果值<input v-model.number="form.numericValue" type="number" step="0.001" required /></label><label>单位<input v-model="form.unit" required /></label><label>参考下限<input v-model.number="form.referenceLow" type="number" step="0.001" required /></label><label>参考上限<input v-model.number="form.referenceHigh" type="number" step="0.001" required /></label><label>异常标志<select v-model="form.abnormalFlag"><option value="NORMAL">正常</option><option value="HIGH">偏高</option><option value="LOW">偏低</option><option value="CRITICAL_HIGH">危急偏高</option><option value="CRITICAL_LOW">危急偏低</option></select></label></div><label>报告结论<textarea v-model="form.conclusion" required rows="2" /></label></BusinessActionDialog>
    <ClinicalPageState v-if="resultsQuery.isPending.value" kind="loading" message="正在加载结果与危急值" /><ClinicalPageState v-else-if="issue" kind="error" :code="issue.code" :message="issue.message" @retry="resultsQuery.refetch()" />
    <div v-else-if="resultsQuery.data.value" :class="mode === 'inpatient' ? 'prototype-secondary-grid' : ''">
      <template v-if="false" />
    <div v-else-if="resultsQuery.data.value" class="result-layout"><section class="result-list"><div class="clinical-filter-bar"><label><span>检索报告</span><input v-model="resultSearch" type="search" placeholder="结论、项目或编码" /></label><label><span>分类</span><select v-model="resultFilter"><option value="ALL">全部结果</option><option value="LAB">检验</option><option value="IMAGING">检查</option><option value="ABNORMAL">仅异常</option></select></label><b>{{ filteredResults.length }} 份</b></div><div v-if="filteredResults.length === 0" class="empty-state result-empty"><span>检</span><p>{{ results.length ? '当前筛选下没有报告' : '当前就诊尚无已签发结果' }}</p><small>{{ results.length ? '调整关键词或分类筛选后重试' : '仅已完成执行任务可关联报告' }}</small></div><article v-for="result in filteredResults" :key="result.result_id" class="result-card"><header><div><span class="result-type" :class="result.report_type.toLowerCase()">{{ result.report_type === 'LAB' ? '检验' : '检查' }}</span><strong>{{ result.conclusion }}</strong><small>{{ result.source_system }} · 来源键 …{{ result.source_report_key.slice(-8) }} · 报告 v{{ result.version_no }}</small></div><span class="task-state" :class="result.report_status.toLowerCase()">{{ result.report_status === 'CORRECTED' ? '已更正' : '已签发' }}</span></header><div class="result-observations"><div v-for="observation in result.observations" :key="observation.observation_id"><b>{{ observation.item_name }}</b><span>{{ observation.numeric_value ?? observation.text_value }} {{ observation.unit }}</span><small>{{ observation.reference_low ?? '—' }} – {{ observation.reference_high ?? '—' }}</small><em class="result-flag" :class="observation.abnormal_flag.toLowerCase()">{{ observation.abnormal_flag }}</em></div></div>
      <section v-for="critical in result.critical_values" :key="critical.critical_value_id" class="critical-panel" :class="critical.state.toLowerCase()"><header><strong>危急值责任闭环</strong><span>{{ critical.state === 'OPEN' ? '待接收' : critical.state === 'ACKNOWLEDGED' ? '已接收·待处置' : '已处置' }}</span></header><div v-if="critical.state === 'OPEN'"><p>请与报告者双向复读确认；“查看”不等于接收。</p><button v-if="canReceiveCritical" class="button danger" :disabled="busy === `ack:${critical.critical_value_id}`" @click="acknowledge(critical)">复读并确认接收</button></div><div v-else-if="critical.state === 'ACKNOWLEDGED'"><p>临床评估、采取措施、处置结果与复测决策将分别留痕。</p><button v-if="canDisposeCritical" class="button danger" @click="beginDisposition(critical)">填写处置结果</button></div><p v-else>接收与处置事件已分别留痕，普通批量任务不能改写。</p></section>
      <footer><span>水印 {{ result.data_watermark.slice(0, 12) }}… · 原医嘱 …{{ result.order_id.slice(-8) }}</span><button v-if="canAuthorResult(result)" class="button secondary" @click="beginCorrection(result)">更正报告</button></footer></article></section><aside class="side-card result-safety"><div class="side-card-title"><h2>安全门禁</h2><span>5</span></div><ul><li>检验结果仅检验技师可签发，影像报告仅影像诊断医师可签发或更正。</li><li>报告必须关联正确患者、就诊、医嘱和已完成执行。</li><li>重复来源报告键不会重复入账。</li><li>危急值确认接收后仍必须记录评估、措施、结果和复测决策。</li><li>更正报告只追加版本并保留原报告。</li></ul></aside></div>
      <InpatientPrototypeRail v-if="mode === 'inpatient'" mode="results" :patient-name="developmentCopy.inpatientPatientName" :total-count="results.length" :pending-count="abnormalResults.length" :open-count="criticalValues.filter((item) => item.state !== 'DISPOSED').length" />
    </div>
    <BusinessActionDialog :open="Boolean(dispositionCritical)" title="完成危急值处置" description="接收不等于处置；以下临床事实会分别写入不可变证据。" :eyebrow="mode === 'inpatient' ? '住院检查检验' : '门诊检查检验'" confirm-label="完成处置并留痕" danger :busy="Boolean(busy)" width="wide" @cancel="dispositionCriticalId = null" @confirm="dispose"><template v-if="dispositionCritical"><label>临床评估<textarea v-model="disposition(dispositionCritical).assessment" required /></label><label>采取措施<textarea v-model="disposition(dispositionCritical).actionTaken" required /></label><label>处置结果<textarea v-model="disposition(dispositionCritical).outcome" required /></label><label class="dialog-check"><input v-model="disposition(dispositionCritical).retestRequired" type="checkbox" />需要复测</label></template></BusinessActionDialog>
    <BusinessActionDialog :open="Boolean(correctionResult)" title="追加结果更正版本" description="原报告不可覆盖或删除；更正将生成新版本并保留全部来源。" :eyebrow="mode === 'inpatient' ? '住院检查检验' : '门诊检查检验'" confirm-label="追加更正版本" :busy="Boolean(busy)" width="wide" @cancel="correctionResultId = null" @confirm="correct"><template v-if="correctionResult && correctionById[correctionResult.result_id]"><div class="dialog-grid"><label>更正结果<input v-model.number="correctionById[correctionResult.result_id].value" type="number" step="0.001" /></label><label>更正标志<select v-model="correctionById[correctionResult.result_id].flag"><option value="NORMAL">正常</option><option value="HIGH">偏高</option><option value="LOW">偏低</option><option value="CRITICAL_HIGH">危急偏高</option><option value="CRITICAL_LOW">危急偏低</option></select></label></div><label>更正后结论<textarea v-model="correctionById[correctionResult.result_id].conclusion" required rows="2" /></label><label>更正原因<textarea v-model="correctionById[correctionResult.result_id].reason" required rows="2" /></label></template></BusinessActionDialog>
  </section>
</template>
