/* v0.11 core specialty workflows and outpatient-local medical record */
const specialtyDefinitions={
  obgyn:{label:'妇产科',icon:'妇',sub:'妇科、产科、围产与母婴安全',metrics:[['今日门诊','68'],['在院孕产妇','42'],['高危妊娠','7'],['待分娩','5']],flow:['建档/分诊','孕产评估','产程/手术','母婴交接','产后随访'],fields:[['孕产史','孕3产1 · G3P1'],['末次月经/预产期','2026-01-18 / 2026-10-25'],['孕周','29+4 周'],['高危评分','橙色 · 瘢痕子宫'],['胎位/胎心','头位 / 148次/分'],['宫高/腹围','28cm / 91cm'],['血型/抗体','O+ / 阴性'],['母婴关联','待分娩后建立']],docs:['孕产妇建档','产前检查记录','产程图','分娩记录','新生儿出生记录','产后访视'],risk:'孕妇血压 158/102 mmHg 且尿蛋白 2+，触发子痫前期硬阻断',care:['高危妊娠分层','胎心监护接入','产程图与宫口记录','分娩/剖宫产核查','母婴双身份交接','产后出血预警'],qc:['孕周与预产期一致性','产程记录时限','母婴腕带双核对','产后出血量闭环','知情同意与手术分级']},
  reproductive:{label:'生殖医学',icon:'生',sub:'不孕评估、周期、胚胎与生殖伦理',metrics:[['在管周期','126'],['今日取卵','9'],['移植计划','7'],['冷冻胚胎','1,842']],flow:['夫妇建档','评估/方案','促排监测','取卵/实验室','移植/随访'],fields:[['夫妇关联','女方 P10086 / 男方 P10087'],['不孕年限','3 年'],['周期类型','IVF-ET 长方案'],['周期日','D10'],['卵泡监测','左 6 / 右 5'],['激素结果','E2 1860 pg/mL'],['配子/胚胎权限','双人复核'],['伦理同意','当前周期已签']],docs:['夫妇评估记录','周期方案','促排监测','取卵记录','胚胎培养记录','移植与随访'],risk:'胚胎移植前夫妇身份与冷冻载杆编号未完成双人核验',care:['夫妇联合建档','周期方案审批','用药与超声监测','取卵/受精/培养','胚胎评级与冷冻','移植/妊娠随访'],qc:['配子胚胎双人核验','周期用药剂量','实验室环境记录','知情同意有效期','冷冻库存账实一致']},
  pediatrics:{label:'儿科',icon:'儿',sub:'儿童就诊、生长发育与体重剂量安全',metrics:[['今日患儿','93'],['发热患儿','21'],['待复评','8'],['剂量阻断','3']],flow:['监护人核验','年龄分诊','生长评估','诊疗用药','健康教育'],fields:[['监护人','母亲 王敏 · 已核验'],['出生日期/月龄','2021-11-06 / 57月'],['体重/身高','18.2kg / 108cm'],['体表面积','0.73m²'],['喂养/发育','普食 / 同龄相符'],['疫苗史','按程序 · 待核流感'],['剂量计算依据','18.2kg · 今日 09:12'],['学校/接触史','幼儿园 · 流感接触']],docs:['儿科门诊病历','生长发育评估','用药剂量单','传染病筛查','监护人告知','随访计划'],risk:'阿奇霉素候选剂量超过按 18.2kg 计算的单日上限',care:['监护人授权','年龄/体重采集','生长曲线评估','儿童剂量计算','疫苗/传染病核查','复诊与健康教育'],qc:['年龄月龄自动换算','体重时效性','剂量单位与上限','监护人签署','危重儿童分诊时限']},
  neonatal:{label:'新生儿科',icon:'新',sub:'出生事件、母婴关联与新生儿监护',metrics:[['在科新生儿','38'],['NICU','19'],['早产儿','11'],['喂养风险','5']],flow:['出生接收','母婴核验','胎龄评估','监护喂养','出院随访'],fields:[['母亲/分娩事件','李娜 / DEL-260814-09'],['出生时间','2026-08-14 08:26'],['胎龄/出生体重','34+2周 / 2180g'],['Apgar','8-9-10'],['腕带/足印','双腕带一致 / 已采'],['喂养','母乳+强化 · 12ml/3h'],['黄疸','TcB 10.6mg/dL'],['筛查','听力/遗传代谢待完成']],docs:['出生记录','入室评估','新生儿病程','喂养记录','筛查记录','出院交接'],risk:'新生儿腕带与母亲分娩事件号不一致，禁止接收入科及采集标本',care:['出生事件接收','母婴关系建立','胎龄/Apgar评估','保温监护与喂养','黄疸/感染筛查','出院与儿童保健交接'],qc:['母婴双身份一致','胎龄体重单位','喂养出入量','新生儿筛查闭环','出院去向与监护人确认']},
  mental:{label:'精神心理科',icon:'心',sub:'特殊隐私、风险评估与保护性医疗',metrics:[['今日接诊','47'],['高风险观察','6'],['保护约束','2'],['随访逾期','9']],flow:['授权核验','精神检查','风险分层','诊疗干预','随访管理'],fields:[['就诊授权','本人同意 · 特殊隐私'],['监护人/联系人','姐姐 陈敏 · 应急可联系'],['精神检查','意识清 · 定向完整'],['自杀风险','中风险 · C-SSRS 4'],['暴力风险','低风险'],['量表','PHQ-9 18 / GAD-7 13'],['保护性医疗','当前未启用'],['药物依从','近 7 日漏服 2 次']],docs:['精神科初诊记录','精神检查','自杀/暴力风险评估','保护性措施记录','心理治疗记录','随访危机计划'],risk:'患者表达明确自杀计划且有可获得工具，禁止普通结束就诊并启动危机处置',care:['特殊授权确认','精神状态检查','自杀暴力风险评估','药物/心理方案','保护措施审批复核','危机随访与转介'],qc:['敏感病历最小访问','风险量表完整性','保护措施时限复核','监护人/本人告知','危机事件交接闭环']},
  ophthalmology:{label:'眼科',icon:'眼',sub:'双眼结构化检查、测量与眼科影像',metrics:[['今日检查','112'],['散瞳候诊','18'],['手术计划','9'],['眼压预警','4']],flow:['视力检查','眼压/验光','裂隙灯/眼底','诊断计划','手术随访'],fields:[['裸眼视力 OD/OS','0.3 / 0.6'],['矫正视力 OD/OS','0.8 / 1.0'],['眼压 OD/OS','26 / 18 mmHg'],['屈光度','OD -3.25 / OS -2.75'],['前节','OD 晶状体混浊'],['眼底','视盘 C/D 0.7/0.5'],['OCT/眼底照相','已关联 Study 2项'],['手术眼别','右眼 · 待二次核验']],docs:['眼科门诊病历','视力验光单','眼压记录','裂隙灯/眼底记录','手术计划','术后随访'],risk:'右眼手术计划与知情同意书眼别不一致，禁止进入术前核查',care:['双眼身份建模','视力验光眼压','结构化部位图','OCT/眼底影像','眼科手术核查','视功能随访'],qc:['OD/OS 不混淆','测量设备校准','散瞳禁忌核查','手术眼别一致','图像报告版本关联']},
  ent:{label:'耳鼻咽喉科',icon:'耳',sub:'耳鼻咽喉分区检查、听力与内镜',metrics:[['今日接诊','76'],['听力检查','24'],['内镜待报告','11'],['气道风险','2']],flow:['分区主诉','专科查体','听力/内镜','诊疗操作','复诊随访'],fields:[['患侧/部位','右耳'],['耳镜','鼓膜完整 · 充血'],['纯音测听','右耳 45dB HL'],['声导抗','B型'],['鼻内镜','双下鼻甲肥大'],['咽喉镜','声带活动对称'],['气道风险','无急性梗阻'],['设备检查','Study ENT-260814-18']],docs:['耳科病历','鼻科病历','咽喉科病历','听力学报告','内镜记录','操作与随访'],risk:'喉镜发现疑似气道狭窄且血氧下降，禁止普通候诊并转急诊处置',care:['耳鼻喉分区定位','听力/前庭评估','内镜图像采集','异物/出血处置','手术与标本送检','听力语言随访'],qc:['左右侧与部位一致','内镜图像可追溯','气道风险升级','操作知情同意','病理标本部位核对']},
  dental:{label:'口腔科',icon:'齿',sub:'牙位、牙周、影像与口腔治疗计划',metrics:[['今日就诊','84'],['治疗椅占用','16'],['影像待阅','13'],['种植计划','6']],flow:['口腔检查','牙位记录','影像评估','治疗计划','操作随访'],fields:[['主诉牙位','FDI 46'],['牙体情况','46 远中邻面龋'],['牙周袋深度','46MB 5mm'],['松动度','0'],['咬合关系','安氏 I 类'],['全景片/CBCT','Study DENT-260814-33'],['治疗计划','根管治疗+全冠'],['材料/植入物','待批次扫码']],docs:['口腔初诊病历','牙位图','牙周检查表','影像诊断','治疗计划','操作与材料记录'],risk:'拔牙申请牙位 36 与当前影像标注 46 不一致，禁止操作',care:['牙位图检查','牙周量化','口腔影像关联','分期治疗计划','材料植入物追踪','术后复诊'],qc:['FDI 牙位一致','左右上下颌核对','材料批次追溯','麻醉与过敏核查','收费项目与操作对账']},
  dermatology:{label:'皮肤科',icon:'肤',sub:'皮损图谱、面积评分与皮肤影像',metrics:[['今日接诊','91'],['皮肤镜','27'],['生物制剂','8'],['急性重症','1']],flow:['皮损定位','形态评估','影像/病理','治疗计划','疗效随访'],fields:[['皮损部位','躯干/双上肢'],['形态','红斑鳞屑斑块'],['体表面积 BSA','12%'],['PASI/SCORAD','PASI 14.6'],['皮肤镜','Study DERM-260814-21'],['过敏原/接触史','金属镍可疑'],['生物制剂筛查','结核/乙肝待复核'],['医学摄影授权','本次诊疗授权']],docs:['皮肤科病历','皮损图谱','量表评分','皮肤镜记录','医学摄影','生物制剂随访'],risk:'拟启用生物制剂但结核筛查结果未回，禁止处方生效',care:['皮损部位图谱','面积/严重度量表','皮肤镜/摄影','病理标本关联','光疗/生物制剂','疗效与不良反应随访'],qc:['皮损位置版本化','医学照片授权','量表计算校验','用药前筛查','病理部位一致']},
  tcm:{label:'中医科',icon:'中',sub:'四诊、证候、治法、方药与中医质控',metrics:[['今日接诊','73'],['待辨证','12'],['中药处方','41'],['配伍预警','3']],flow:['四诊采集','辨病辨证','治法方药','调剂执行','疗效随访'],fields:[['望诊','面色少华 · 舌淡胖'],['舌象','淡胖 · 苔白腻'],['脉象','沉细'],['闻问切','乏力纳差 · 畏寒'],['中医病名','眩晕病'],['证候','气血亏虚证'],['治法','益气养血、健脾和胃'],['方剂','归脾汤加减']],docs:['中医门诊病历','四诊记录','辨证论治','中药处方','针灸/推拿记录','疗效评价'],risk:'候选方含附子且未完成剂量、炮制、煎煮和禁忌核验，禁止提交',care:['四诊结构化采集','病名证候双编码','治法方剂关联','饮片配伍审方','针灸推拿穴位','证候疗效随访'],qc:['理法方药一致','毒性饮片门禁','十八反十九畏','中西药相互作用','中医术语与代码版本']}
};

const specialtyKeys=Object.keys(specialtyDefinitions);
const specialtyRoutes=['specialty-center',...specialtyKeys.flatMap(k=>[`${k}-workbench`,`${k}-record`,`${k}-care`,`${k}-qc`])];
pages.splice(4,0,{id:'specialty-center',label:'核心专科工作台',icon:'专',group:'临床工作域',count:'10'});

function outpatientRecord(){return pageHead('门诊病历','门诊工作域 · 当前就诊 OP20260813-0842 · 书写、质控、签署不离开门诊上下文','<button class="btn" data-jump="record">跨域：进入全院病历中心</button><button class="btn primary">提交并签署</button>')+patientStrip()+`<div class="grid record-hub"><section class="card"><div class="card-head">门诊病历正文 <span class="status amber">草稿 v4</span></div><div class="card-body"><div class="form-row"><div class="label">主诉 *</div><div class="field">头晕、血压升高 1 周</div></div><div class="form-row"><div class="label">现病史 *</div><div class="field textarea ai">患者一周前出现头晕，家庭血压最高 168/96 mmHg。<span class="source-tag">AI 草稿 · 待确认</span></div></div><div class="form-row"><div class="label">既往史/过敏史</div><div class="field">高血压 8 年；青霉素严重过敏</div></div><div class="form-row"><div class="label">查体</div><div class="field">BP 156/92 mmHg，HR 76 次/分，心肺未见明显异常</div></div><div class="form-row"><div class="label">诊断与计划 *</div><div class="field textarea">原发性高血压 2级；调整方案后 2 周复诊，复查电解质与肾功能</div></div><div class="notice hard"><div class="notice-title">签署阻断 1 项</div>分诊记录“一过性胸闷”尚未在现病史中核对处置。</div></div><div class="footer-actions"><span class="save-state">● 已自动保存</span><button class="btn">暂存</button><button class="btn">运行质控</button><button class="btn primary">提交并签署</button></div></section><aside class="card"><div class="card-head">本次门诊闭环</div><div class="card-body">${[['病历完整性','8/9 项'],['诊断','I10.x03'],['处方','2 项待审'],['检验检查','血钾待处置'],['随访计划','2 周后'],['签署','硬阻断 1']].map(x=>`<div class="folder-row">${x[0]}<span>${x[1]}</span></div>`).join('')}<div class="notice info"><div class="notice-title">域内路由</div>本页始终高亮“门诊工作台”；进入全院病历中心时使用显式跨域按钮。</div></div></aside></div>`}

function specialtyNav(active){return `<div class="center-nav specialty-nav"><b>核心专科</b><button class="${active==='specialty-center'?'active':''}" data-jump="specialty-center">总览</button>${specialtyKeys.map(k=>`<button class="${active.startsWith(k+'-')?'active':''}" data-jump="${k}-workbench">${specialtyDefinitions[k].label}</button>`).join('')}</div>`}
function specialtySubNav(key,active){const d=specialtyDefinitions[key];return `<div class="subpage-nav"><b>${d.label}</b>${[['workbench','工作台'],['record','专科病历'],['care','关键流程'],['qc','质控安全']].map(x=>`<button class="${active===key+'-'+x[0]?'active':''}" data-jump="${key}-${x[0]}">${x[1]}</button>`).join('')}</div>`}
function specialtyCenter(){return pageHead('核心专科工作台','10 类核心专科共享临床内核，同时保留专业字段、状态机、设备接口与安全门禁','<button class="btn" data-jump="specialty-coverage">查看全科室支持矩阵</button><button class="btn primary">配置专科排班</button>')+`<div class="hub-hero"><div><span>SPECIALTY CLINICAL WORKSPACE</span><h2>专科深度不是换模板，而是完整的专业诊疗闭环</h2><p>妇产、生殖、儿科、新生儿、精神、眼科、耳鼻喉、口腔、皮肤和中医均有独立工作台、病历、关键流程与质控安全页面。</p></div><div class="hub-score"><b>10/10</b><span>核心专科原型</span></div></div><div class="hub-module-grid">${specialtyKeys.map(k=>{const d=specialtyDefinitions[k];return `<button class="hub-module" data-jump="${k}-workbench"><span>${d.icon}</span><b>${d.label}</b><p>${d.sub}</p><i>进入完整专科工作流 →</i></button>`}).join('')}</div>`}
function specialtyPage(key,mode){const d=specialtyDefinitions[key];if(mode==='workbench')return pageHead(`${d.label}工作台`,`${d.sub} · 当前班次与患者队列`,`<button class="btn">交班清单</button><button class="btn primary" data-jump="${key}-record">接诊当前患者</button>`)+`<div class="metric-grid compact-metrics">${d.metrics.map((x,i)=>`<div class="metric"><div class="name">${x[0]}</div><div class="value ${i===2?'danger-text':''}">${x[1]}</div><div class="trend">可下钻到患者与任务</div></div>`).join('')}</div><div class="grid coverage-layout"><section class="card"><div class="card-head">专科诊疗队列 <span class="sub">按风险与时限排序</span></div><table class="table"><thead><tr><th>患者/对象</th><th>当前阶段</th><th>关键资料</th><th>状态</th></tr></thead><tbody><tr><td><b>当前高风险患者</b></td><td>${d.flow[1]}</td><td>${d.fields[2][1]}</td><td><span class="status red">需立即处理</span></td></tr><tr><td>复诊患者 02</td><td>${d.flow[3]}</td><td>${d.fields[4][1]}</td><td><span class="status amber">待复核</span></td></tr><tr><td>新接诊患者 03</td><td>${d.flow[0]}</td><td>身份与授权已核验</td><td><span class="status green">可接诊</span></td></tr></tbody></table><div class="coverage-flow">${d.flow.map((x,i)=>`<span><i>${i+1}</i>${x}</span>`).join('<b>›</b>')}</div></section><aside class="card"><div class="card-head">最高风险</div><div class="card-body"><div class="notice hard"><div class="notice-title">专业硬阻断</div>${d.risk}</div>${d.fields.slice(0,5).map(x=>`<div class="folder-row">${x[0]}<span>${x[1]}</span></div>`).join('')}<button class="btn primary full-btn" data-jump="${key}-care">进入关键流程</button></div></aside></div>`;
  if(mode==='record')return pageHead(`${d.label}专科病历`,`${d.sub} · 专科字段与法定通用病历共同签署`,`<button class="btn">调阅历次专科记录</button><button class="btn primary">运行签署前质控</button>`)+patientStrip()+`<div class="grid admin-overview"><section class="card"><div class="card-head">专科结构化字段</div><div class="card-body"><div class="setting-grid">${d.fields.map(x=>`<div><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}</div><div class="section-title">专科文书目录</div><div class="workflow-cards">${d.docs.map((x,i)=>`<button><b>${x}</b><span>${i<2?'草稿/待确认':'按诊疗事件创建'}</span></button>`).join('')}</div></div></section><aside class="card"><div class="card-head">AI 与来源</div><div class="card-body"><div class="notice ai"><div class="notice-title">✦ 专科病历助手</div>仅基于当前患者、当前就诊和已授权专科来源生成草稿；专业测量与设备数据不可由模型臆造。</div><div class="notice hard"><div class="notice-title">签署前核验</div>${d.risk}</div>${d.qc.slice(0,4).map(x=>`<div class="folder-row">${x}<span>待核验</span></div>`).join('')}</div></aside></div>`;
  if(mode==='care')return pageHead(`${d.label}关键诊疗流程`,`${d.flow.join(' → ')}`,`<button class="btn">查看流程版本</button><button class="btn primary">进入当前任务</button>`)+`<div class="grid coverage-layout"><section class="card"><div class="card-head">专业状态机与任务</div><div class="card-body"><div class="coverage-flow">${d.flow.map((x,i)=>`<span><i>${i+1}</i>${x}</span>`).join('<b>›</b>')}</div><div class="workflow-cards">${d.care.map((x,i)=>`<button><b>${x}</b><span>${i===0?'已完成':i===1?'进行中':'待前置条件'}</span></button>`).join('')}</div></div></section><aside class="card"><div class="card-head">安全、设备与恢复</div><div class="card-body"><div class="notice hard"><div class="notice-title">当前阻断</div>${d.risk}</div>${[['设备/外部数据','按来源、采集时间和版本关联'],['权限','专业资质 + 患者关系 + 当前任务'],['中断恢复','保留已完成节点与原始事实'],['重复提交','幂等返回原业务结果'],['转科/转院','未完任务与风险显式交接']].map(x=>`<div class="folder-row">${x[0]}<span>${x[1]}</span></div>`).join('')}</div></aside></div>`;
  return pageHead(`${d.label}质控与安全`,`运行质控、签署前门禁、终末质控、科室指标与整改闭环`,`<button class="btn">抽取质控样本</button><button class="btn primary">创建整改任务</button>`)+`<div class="grid coverage-layout"><section class="card"><div class="card-head">专科质量规则</div><table class="table"><thead><tr><th>规则</th><th>阶段</th><th>严重度</th><th>处置</th></tr></thead><tbody>${d.qc.map((x,i)=>`<tr><td><b>${x}</b></td><td>${i<2?'书写中':i<4?'签署前':'终末质控'}</td><td><span class="status ${i===0?'red':i<3?'amber':'blue'}">${i===0?'硬阻断':'需复核'}</span></td><td>${i===0?'修正后重跑':'转人工/整改'}</td></tr>`).join('')}</tbody></table></section><aside class="card"><div class="card-head">缺陷证据</div><div class="card-body"><div class="notice hard"><div class="notice-title">不可豁免缺陷</div>${d.risk}</div>${[['规则版本','SPECIALTY-QC-2026.08'],['责任科室',d.label],['整改时限','本次业务状态完成前'],['复核方式','专业人员人工复核'],['审计','原值、修改、签署均保留']].map(x=>`<div class="folder-row">${x[0]}<span>${x[1]}</span></div>`).join('')}</div></aside></div>`}

renderers['opd-record']=outpatientRecord;
renderers['specialty-center']=specialtyCenter;
specialtyKeys.forEach(k=>['workbench','record','care','qc'].forEach(mode=>{renderers[`${k}-${mode}`]=()=>specialtyPage(k,mode)}));
const specialtyCoverageV11=renderers['specialty-coverage'];
renderers['specialty-coverage']=()=>specialtyCoverageV11().replace('专科包待交付</div><div class="value">8</div><div class="trend">不宣称完整生产支持','核心专科原型</div><div class="value">10</div><div class="trend">40 个专业深页已完成');
const clinicalBeforeSpecialty=renderers.clinical;
renderers.clinical=()=>clinicalBeforeSpecialty();

const renderBeforeSpecialty=render;
render=function(){renderBeforeSpecialty();const main=document.querySelector('.main');if(specialtyRoutes.includes(current)&&main){main.insertAdjacentHTML('afterbegin',specialtyNav(current));if(current!=='specialty-center'){const key=specialtyKeys.find(k=>current.startsWith(k+'-'));if(key)main.insertAdjacentHTML('afterbegin',specialtySubNav(key,current))}document.querySelectorAll('.nav-item.active').forEach(x=>x.classList.remove('active'));document.querySelector('[data-page="specialty-center"]')?.classList.add('active');document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>{current=b.dataset.jump;location.hash=current;render()})}};
const requestedV11Route=location.hash.slice(1);
if(requestedV11Route==='opd-record'||specialtyRoutes.includes(requestedV11Route))current=requestedV11Route;
render();
