create table medical_agent_question_example (
  agent_code varchar(128) not null,
  release_version varchar(64) not null,
  example_order integer not null check (example_order > 0),
  question_text varchar(512) not null check (length(trim(question_text)) between 4 and 512),
  primary key (agent_code, release_version, example_order),
  foreign key (agent_code, release_version)
    references medical_agent_release(agent_code, release_version)
);

insert into medical_agent_question_example(agent_code, release_version, example_order, question_text)
values
('ENCOUNTER_SUMMARIZER','1.0.0',1,'请按时间顺序总结这次就诊的关键事实、变化和仍需确认的问题。'),
('ENCOUNTER_SUMMARIZER','1.0.0',2,'请帮我整理本次就诊与既往记录相比有哪些新变化，并标注信息来源。'),
('DOCUMENT_DRAFTER','1.0.0',1,'请根据当前已确认信息起草病历草稿，并把缺失内容单独列出。'),
('DOCUMENT_DRAFTER','1.0.0',2,'请按医院病历模板整理这次诊疗记录，未确认的信息不要补写。'),
('RECORD_QC','1.0.0',1,'请检查当前病历是否存在前后矛盾、关键缺项或时间顺序问题。'),
('RECORD_QC','1.0.0',2,'这份病历签署前还需要补充或核对哪些内容？'),
('RESULT_FOLLOWUP_COORDINATOR','1.0.0',1,'请汇总本次检查检验结果的异常变化和仍未闭环的事项。'),
('RESULT_FOLLOWUP_COORDINATOR','1.0.0',2,'请找出需要医生关注、复查或安排随访的结果，并说明依据。'),
('CARE_COORDINATOR','1.0.0',1,'请整理当前患者会诊、转科、出院和随访中尚未完成的协同事项。'),
('CARE_COORDINATOR','1.0.0',2,'请按责任人和完成时限整理下一步诊疗协同计划。'),
('PRE_VISIT_SUMMARIZER','1.0.0',1,'患者就诊前有哪些重要病史、过敏、用药和未完成事项需要先关注？'),
('TRIAGE_CONTEXT_SUMMARIZER','1.0.0',1,'请根据主诉、生命体征和分诊记录整理需要优先关注的情况。'),
('ACTIVE_ENCOUNTER_SUMMARIZER','1.0.0',1,'请总结本次接诊新增的症状、检查结果和待确认问题。'),
('INPATIENT_DAILY_SUMMARIZER','1.0.0',1,'请汇总患者过去24小时的病情变化、检查结果、治疗调整和未完成任务。'),
('PERIOPERATIVE_CONTEXT_SUMMARIZER','1.0.0',1,'请整理围术期关键事实，并提示手术部位、侧别或术前核查中的缺项。'),
('DISCHARGE_READINESS_SUMMARIZER','1.0.0',1,'请评估患者目前是否具备出院准备条件，并列出仍需完成的事项。'),
('OUTPATIENT_NOTE_DRAFTER','1.0.0',1,'请根据本次门诊已确认信息起草门诊病历，缺失项请标注待补充。'),
('EMERGENCY_NOTE_DRAFTER','1.0.0',1,'请按时间线起草急诊记录，并提示关键时间点或处置记录缺口。'),
('ADMISSION_NOTE_DRAFTER','1.0.0',1,'请根据现有病史、查体和辅助检查起草入院记录。'),
('FIRST_COURSE_DRAFTER','1.0.0',1,'请起草首次病程记录，区分诊断依据、鉴别诊断和诊疗计划。'),
('PROGRESS_NOTE_DRAFTER','1.0.0',1,'请根据今天的病情变化、检查结果和治疗调整起草病程记录。'),
('WARD_ROUND_NOTE_DRAFTER','1.0.0',1,'请根据本次查房实际记录起草查房记录，并标出尚未确认的内容。'),
('CONSULT_NOTE_DRAFTER','1.0.0',1,'请整理会诊目的、患者摘要和需要会诊科室回答的具体问题。'),
('PERIOPERATIVE_NOTE_DRAFTER','1.0.0',1,'请根据已确认的手术信息起草围术期文书，并列出高风险缺项。'),
('NURSING_HANDOFF_DRAFTER','1.0.0',1,'请整理本班病情变化、用药执行和未完成任务，起草护理交班内容。'),
('DISCHARGE_NOTE_DRAFTER','1.0.0',1,'请起草出院小结，并单列出院用药、复诊安排和未回结果。'),
('WRITING_QC_REVIEWER','1.0.0',1,'请在不打断书写的情况下提示当前病历的结构缺项和前后不一致。'),
('PRE_SIGN_QC_REVIEWER','1.0.0',1,'这份病历签署前有哪些完整性、时序或诊疗一致性问题需要处理？'),
('ACTIVE_RECORD_QC_REVIEWER','1.0.0',1,'请检查当前在院病历中的逾期记录、重复内容和未完成责任任务。'),
('TERMINAL_RECORD_QC_REVIEWER','1.0.0',1,'请列出病历归档前仍需整改的文书、编码和闭环问题。'),
('CORRECTION_CONSISTENCY_REVIEWER','1.0.0',1,'这次病历更正影响了哪些文书、引用结果或后续任务？'),
('NEW_RESULT_INTAKE_AGENT','1.0.0',1,'请整理今天新增或更正的检查检验结果，并标出需要处理的异常项。'),
('RESULT_TREND_REVIEWER','1.0.0',1,'请比较近期同类结果的变化趋势，并提示单位或参考范围不可比的情况。'),
('CRITICAL_RESULT_CONTEXT_AGENT','1.0.0',1,'请汇总这项危急值的通知、接收、处置和复核状态。'),
('PENDING_RESULT_TRACKER','1.0.0',1,'请列出当前仍未报告、部分报告或正在更正的检查检验结果。'),
('FOLLOWUP_TASK_PLANNER','1.0.0',1,'请把已确认的复查和随访计划整理成责任人、时间和任务清单。'),
('CORRECTED_RESULT_RECONCILER','1.0.0',1,'这项更正结果会影响哪些病历内容、诊疗判断或随访任务？'),
('CONSULT_PREPARATION_AGENT','1.0.0',1,'请准备会诊摘要，并列出需要目标科室重点回答的问题和缺失资料。'),
('MDT_BRIEF_AGENT','1.0.0',1,'请生成本次多学科讨论简报，突出主要分歧和待决策问题。'),
('TRANSFER_HANDOFF_AGENT','1.0.0',1,'请整理转科交接要点，包括当前病情、未完成医嘱和接收注意事项。'),
('DISCHARGE_TRANSITION_AGENT','1.0.0',1,'请把出院用药、健康教育、复诊和异常升级条件整理成连续照护计划。'),
('FOLLOWUP_COORDINATION_AGENT','1.0.0',1,'请根据已确认计划生成随访安排，并标出提醒时间和异常升级条件。'),
('TASK_RECONCILIATION_AGENT','1.0.0',1,'请核对当前开放、重复、逾期和已转派任务，并给出处理建议。');
