-- Compatibility marker.
--
-- This migration was accidentally renumbered from V318 to V321 after V318 had
-- already shipped to development databases. The real schema change remains in
-- V318 so existing and fresh databases share the same Flyway history. Keeping
-- this no-op marker reserves V321 without attempting to recreate the columns,
-- constraints, or index.
