-- 补齐 V343 新增的 5 个主医助的组合发布与组合节点：
-- V343 只注册了医助本身，未注册可执行的组合（composition），导致这些医助无法被调度。
insert into medical_agent_composition_release(
  composition_code, release_version, root_agent_code, max_depth, status)
values
('INFECTION_SURVEILLANCE_DEFAULT','1.0.0','INFECTION_SURVEILLANCE',1,'ACTIVE'),
('INSURANCE_COMPLIANCE_DEFAULT','1.0.0','INSURANCE_COMPLIANCE',1,'ACTIVE'),
('MEDICAL_TECH_SCHEDULING_DEFAULT','1.0.0','MEDICAL_TECH_SCHEDULING',1,'ACTIVE'),
('RESEARCH_FOLLOWUP_DEFAULT','1.0.0','RESEARCH_FOLLOWUP',1,'ACTIVE'),
('PATIENT_EDUCATION_DEFAULT','1.0.0','PATIENT_EDUCATION',1,'ACTIVE');

insert into medical_agent_composition_node(
  composition_code, release_version, child_agent_code, stage_code, node_order, critical, parallel_group)
values
('INFECTION_SURVEILLANCE_DEFAULT','1.0.0','INFECTION_CASE_REVIEWER','INFECTION_CASE',1,true,'STAGE'),
('INFECTION_SURVEILLANCE_DEFAULT','1.0.0','OUTBREAK_ALERT_ASSESSOR','OUTBREAK',2,true,'STAGE'),
('INFECTION_SURVEILLANCE_DEFAULT','1.0.0','NOTIFIABLE_REPORT_ASSISTANT','NOTIFIABLE',3,false,'STAGE'),
('INSURANCE_COMPLIANCE_DEFAULT','1.0.0','DRG_CODING_REVIEWER','DRG_CODING',1,false,'STAGE'),
('INSURANCE_COMPLIANCE_DEFAULT','1.0.0','CHARGE_RATIONALITY_REVIEWER','CHARGE',2,false,'STAGE'),
('MEDICAL_TECH_SCHEDULING_DEFAULT','1.0.0','EXAM_SLOT_PLANNER','EXAM_SLOT',1,false,'STAGE'),
('MEDICAL_TECH_SCHEDULING_DEFAULT','1.0.0','EQUIPMENT_UTILIZATION_REVIEWER','EQUIPMENT',2,false,'STAGE'),
('RESEARCH_FOLLOWUP_DEFAULT','1.0.0','COHORT_ENROLLMENT_ASSISTANT','COHORT',1,false,'STAGE'),
('RESEARCH_FOLLOWUP_DEFAULT','1.0.0','OUTCOME_COLLECTION_ASSISTANT','OUTCOME',2,false,'STAGE'),
('PATIENT_EDUCATION_DEFAULT','1.0.0','DISCHARGE_MEDICATION_GUIDE','MEDICATION_GUIDE',1,false,'STAGE'),
('PATIENT_EDUCATION_DEFAULT','1.0.0','FOLLOWUP_REMINDER_ASSISTANT','FOLLOWUP_REMINDER',2,false,'STAGE');
